#!/usr/bin/env python3.12
"""Render the per-language internal SDK API reference from the RPC-coverage projection.

The four ``sdks/<language>/api.md`` documents are the SDK equivalent of the
architecture blueprint render: committed documentation whose whole body is derived
from a governed source, checked for drift by ``just docs`` and rewritten by
``just generate``.

Their single input is ``sdks/rpc-coverage.generated.json``, which the atomic
contract transaction derives from the candidate descriptor. Nothing here reads the
SDK sources, so an api.md can never claim a method the descriptor does not declare,
and a reference cannot silently drift from the RPC estate the way a hand-written
list would.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, cast

COVERAGE_PATH = Path("sdks/rpc-coverage.generated.json")
PROJECTION_SCHEMA = "mindclade.internal-sdk-rpc-coverage-projection/v2"

LANGUAGE_DIRECTORIES = {
    "go": Path("sdks/go"),
    "python": Path("sdks/python"),
    "rust": Path("sdks/rust"),
    "typescript": Path("sdks/typescript"),
}

LANGUAGE_TITLES = {
    "go": "Go",
    "python": "Python",
    "rust": "Rust",
    "typescript": "TypeScript",
}

CLASSIFICATION_NOTES = {
    "ergonomic": "ergonomic facade",
    "raw-only": "raw generated transport only",
    "unsupported": "not exposed",
}


class ReferenceError(Exception):
    """Raised when the coverage projection cannot produce a reference."""


def load_coverage(root: Path) -> dict[str, Any]:
    path = root / COVERAGE_PATH
    try:
        value: object = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ReferenceError(f"cannot read {COVERAGE_PATH}: {error}") from error
    if not isinstance(value, dict):
        raise ReferenceError(f"{COVERAGE_PATH} must be a JSON object")
    coverage = cast(dict[str, Any], value)
    if coverage.get("schema_version") != PROJECTION_SCHEMA:
        raise ReferenceError(
            f"{COVERAGE_PATH} is not a {PROJECTION_SCHEMA} document; "
            "regenerate it with `just generate-contracts`"
        )
    for field in ("descriptor_digest", "languages", "rpcs"):
        if field not in coverage:
            raise ReferenceError(f"{COVERAGE_PATH} has no {field}")
    return coverage


def _rpc_sort_key(rpc: Mapping[str, Any]) -> tuple[str, str, str]:
    return (
        str(rpc.get("facade", "")),
        str(rpc.get("service", "")),
        str(rpc.get("method", "")),
    )


def _shape(rpc: Mapping[str, Any]) -> str:
    if rpc.get("client_streaming") and rpc.get("server_streaming"):
        return "bidirectional stream"
    if rpc.get("server_streaming"):
        return "server stream"
    if rpc.get("client_streaming"):
        return "client stream"
    return "unary"


def _short(type_name: str) -> str:
    return type_name.rsplit(".", 1)[-1] if type_name else ""


def render_language(coverage: Mapping[str, Any], language: str) -> str:
    if language not in cast(list[str], coverage["languages"]):
        raise ReferenceError(f"coverage projection does not cover {language}")

    rpcs = sorted(cast(list[dict[str, Any]], coverage["rpcs"]), key=_rpc_sort_key)
    title = LANGUAGE_TITLES[language]

    lines: list[str] = [
        f"# {title} internal SDK API reference",
        "",
        "<!-- Generated by tools/docs/render_sdk_api_reference.py. DO NOT EDIT. -->",
        "",
        "This reference is rendered from `sdks/rpc-coverage.generated.json`, which the",
        "atomic contract transaction derives from the candidate protobuf descriptor. Run",
        "`just generate` to rewrite it and `just docs` to prove it is current.",
        "",
        f"- Candidate descriptor digest: `{coverage['descriptor_digest']}`",
        f"- Services: {len({str(rpc['service']) for rpc in rpcs})}",
        f"- RPCs: {len(rpcs)}",
        "",
        "Every request and response type below is the generated protobuf message named by the",
        "descriptor. The facade accepts and returns those messages directly; it never defines a",
        "parallel wire model.",
        "",
    ]

    facades: dict[str, list[dict[str, Any]]] = {}
    for rpc in rpcs:
        facades.setdefault(str(rpc.get("facade", "")), []).append(rpc)

    lines.append("## Namespaces")
    lines.append("")
    lines.append("| Namespace | Service | RPCs | Owner |")
    lines.append("| --- | --- | --- | --- |")
    for facade in sorted(facades):
        entries = facades[facade]
        services = sorted({str(entry["service"]) for entry in entries})
        owners = sorted({str(entry["owner"]) for entry in entries})
        lines.append(
            f"| `{facade}` | {', '.join(f'`{service}`' for service in services)} "
            f"| {len(entries)} | {', '.join(owners)} |"
        )
    lines.append("")

    for facade in sorted(facades):
        entries = sorted(facades[facade], key=_rpc_sort_key)
        lines.append(f"## `{facade}`")
        lines.append("")
        lines.append("| Method | Request | Response | Shape | Exposure |")
        lines.append("| --- | --- | --- | --- | --- |")
        for rpc in entries:
            classification = str(rpc.get("classification", ""))
            note = CLASSIFICATION_NOTES.get(classification, classification)
            reason = str(rpc.get("reason", "") or "")
            exposure = f"{note} — {reason}" if reason else note
            lines.append(
                f"| `{rpc['method']}` "
                f"| `{_short(str(rpc['input_type']))}` "
                f"| `{_short(str(rpc['output_type']))}` "
                f"| {_shape(rpc)} "
                f"| {exposure} |"
            )
        lines.append("")

        targets = sorted(
            {
                str(cast(Mapping[str, Any], rpc["evidence"])[language]["library_target"])
                for rpc in entries
            }
        )
        test_targets = sorted(
            {
                str(cast(Mapping[str, Any], rpc["evidence"])[language]["test_target"])
                for rpc in entries
            }
        )
        lines.append(f"Library target: {', '.join(f'`{target}`' for target in targets)}")
        lines.append("")
        lines.append(f"Test target: {', '.join(f'`{target}`' for target in test_targets)}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def output_path(root: Path, language: str) -> Path:
    return root / LANGUAGE_DIRECTORIES[language] / "api.md"


def run(root: Path, languages: Sequence[str], check: bool) -> int:
    coverage = load_coverage(root)
    stale: list[Path] = []
    for language in languages:
        rendered = render_language(coverage, language)
        destination = output_path(root, language)
        current = destination.read_text(encoding="utf-8") if destination.is_file() else None
        if check:
            if current != rendered:
                stale.append(destination)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(rendered, encoding="utf-8")
        print(f"rendered SDK api reference: {destination.relative_to(root)}")
    if check:
        for destination in stale:
            print(
                f"generated SDK api reference is stale: {destination.relative_to(root)}",
                file=sys.stderr,
            )
        if stale:
            return 1
        print(f"SDK api references are current ({len(languages)} languages)")
    return 0


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--language",
        action="append",
        choices=sorted(LANGUAGE_DIRECTORIES),
        help="render one language; repeatable, defaults to every covered language",
    )
    parser.add_argument(
        "--check", action="store_true", help="fail instead of writing when output differs"
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    languages = cast(list[str] | None, args.language) or sorted(LANGUAGE_DIRECTORIES)
    try:
        return run(cast(Path, args.root).resolve(), languages, bool(args.check))
    except ReferenceError as error:
        print(f"SDK api reference render failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
