BEGIN;

DROP TABLE IF EXISTS workflow_agent_command_receipts;
DROP TABLE IF EXISTS agent_tool_receipt_outputs;
DROP TABLE IF EXISTS agent_tool_receipt_approvals;
DROP TABLE IF EXISTS agent_tool_receipts;
DROP TABLE IF EXISTS agent_tool_call_inputs;
DROP TABLE IF EXISTS agent_tool_call_approvals;
DROP TABLE IF EXISTS agent_tool_calls;
DROP TABLE IF EXISTS agent_decision_evidence;
DROP TABLE IF EXISTS agent_step_decisions;
DROP TABLE IF EXISTS agent_step_observations;
DROP TABLE IF EXISTS agent_step_policy_decisions;
DROP TABLE IF EXISTS agent_steps;
DROP TABLE IF EXISTS agent_run_policies;
DROP TABLE IF EXISTS agent_runs;
DROP TABLE IF EXISTS agent_definition_policies;
DROP TABLE IF EXISTS agent_definition_tools;
DROP TABLE IF EXISTS agent_definition_non_goals;
DROP TABLE IF EXISTS agent_definitions;
DROP TABLE IF EXISTS approval_receipt_consumptions;
DROP TABLE IF EXISTS approval_receipt_input_artifacts;
DROP TABLE IF EXISTS approval_receipts;
DROP TABLE IF EXISTS approval_request_policy_decisions;
DROP TABLE IF EXISTS approval_request_input_artifacts;
DROP TABLE IF EXISTS approval_requests;
DROP TABLE IF EXISTS workflow_transition_active_nodes;
DROP TABLE IF EXISTS workflow_transition_revisions;
DROP TABLE IF EXISTS workflow_run_active_nodes;
DROP TABLE IF EXISTS workflow_runs;
DROP TABLE IF EXISTS workflow_definition_policies;
DROP TABLE IF EXISTS workflow_definition_tools;
DROP TABLE IF EXISTS workflow_definitions;
DROP FUNCTION IF EXISTS reject_workflow_agent_immutable_change();

COMMIT;
