// Code generated by mindclade-contract-codegen 3.1.0; DO NOT EDIT.
// Source: protocols/events/registry.yaml (sha256:4af7a9411472940a7fd385267a76416dedb47753a19ef73d83b118fe8a705901)

package queue

var authoritativeEventRegistrations = []EventRegistration{
	{FullName: "mindclade.events.agent.v1.AgentRunCompleted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/agent/v1/agent_run_completed.proto"},
	{FullName: "mindclade.events.agent.v1.AgentStepDispatched", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/agent/v1/agent_step_dispatched.proto"},
	{FullName: "mindclade.events.agent.v1.ToolReceiptCommitted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/agent/v1/tool_receipt_committed.proto"},
	{FullName: "mindclade.events.artifact.v1.ArtifactCommitted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/artifact/v1/artifact_committed.proto"},
	{FullName: "mindclade.events.artifact.v1.ArtifactQuarantined", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/artifact/v1/artifact_quarantined.proto"},
	{FullName: "mindclade.events.audit.v1.AuditEvent", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/audit/v1/audit_event.proto"},
	{FullName: "mindclade.events.audit.v1.SecurityEvent", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/audit/v1/security_event.proto"},
	{FullName: "mindclade.events.feature.v1.FeatureMaterializationCompleted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/feature/v1/feature_materialization_completed.proto"},
	{FullName: "mindclade.events.job.v1.AttemptCompleted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/job/v1/attempt_completed.proto"},
	{FullName: "mindclade.events.job.v1.AttemptLeased", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/job/v1/attempt_leased.proto"},
	{FullName: "mindclade.events.job.v1.JobRequested", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/job/v1/job_requested.proto"},
	{FullName: "mindclade.events.model.v1.ModelPromoted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/model/v1/model_promoted.proto"},
	{FullName: "mindclade.events.model.v1.ModelRegistered", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/model/v1/model_registered.proto"},
	{FullName: "mindclade.events.model.v1.ModelRevoked", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/model/v1/model_revoked.proto"},
	{FullName: "mindclade.events.training.v1.CheckpointCommitted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/training/v1/checkpoint_committed.proto"},
	{FullName: "mindclade.events.training.v1.ProgressCommitted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/training/v1/progress_committed.proto"},
	{FullName: "mindclade.events.training.v1.TrainingCompleted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/training/v1/training_completed.proto"},
	{FullName: "mindclade.events.training.v1.TrainingStarted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/training/v1/training_started.proto"},
	{FullName: "mindclade.events.transform.v1.TransformExecutionCompleted", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/transform/v1/transform_execution_completed.proto"},
	{FullName: "mindclade.events.workflow.v1.ApprovalRecorded", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/workflow/v1/approval_recorded.proto"},
	{FullName: "mindclade.events.workflow.v1.WorkflowTransitioned", Version: 1, ContentType: "application/x-protobuf; deterministic=true", Source: "events/mindclade/workflow/v1/workflow_transitioned.proto"},
}
