packages:
  - libs/typescript/config
  - libs/typescript/observability
  - libs/typescript/testing

allowBuilds: {}

catalog:
  '@types/node': 24.10.1
  typescript: 5.9.3

catalogMode: strict
cleanupUnusedCatalogs: true
linkWorkspacePackages: false
preferWorkspacePackages: false
sharedWorkspaceLockfile: true
