import type { RetrySafety } from "./retry.js";

const policies = new Map<string, RetrySafety>([
	["/mindclade.internal.artifact.v1.ArtifactService/ResolveArtifactAlias", "safe"],
	["/mindclade.internal.job.v1.OperationService/CancelOperation", "idempotent"],
	["/mindclade.internal.job.v1.OperationService/GetOperation", "safe"],
	["/mindclade.internal.training.v1.TrainingService/CreateTrainingRun", "idempotent"],
	["/mindclade.internal.dataset.v1.DatasetService/CreateDataset", "idempotent"],
	["/mindclade.internal.dataset.v1.DatasetService/GetDataset", "safe"],
	["/mindclade.internal.dataset.v1.DatasetService/ListDatasets", "safe"],
	["/mindclade.internal.dataset.v1.DatasetService/UpdateDataset", "idempotent"],
	["/mindclade.internal.dataset.v1.DatasetService/PublishDatasetRelease", "idempotent"],
	["/mindclade.internal.dataset.v1.DatasetService/RevokeDatasetRelease", "idempotent"],
	["/mindclade.internal.dataset.v1.DatasetService/GetDatasetRelease", "safe"],
	["/mindclade.internal.dataset.v1.DatasetService/ListDatasetReleases", "safe"],
	["/mindclade.internal.model.v1.ModelService/RegisterModel", "idempotent"],
	["/mindclade.internal.model.v1.ModelService/GetModel", "safe"],
	["/mindclade.internal.model.v1.ModelService/ListModels", "safe"],
	["/mindclade.internal.model.v1.ModelService/RegisterModelRelease", "idempotent"],
	["/mindclade.internal.model.v1.ModelService/GetModelRelease", "safe"],
	["/mindclade.internal.model.v1.ModelService/ListModelReleases", "safe"],
	["/mindclade.internal.model.v1.ModelService/PromoteModelRelease", "idempotent"],
	["/mindclade.internal.model.v1.ModelService/RevokeModelRelease", "idempotent"],
	["/mindclade.internal.inference.v1.InferenceService/SubmitInference", "idempotent"],
	["/mindclade.internal.inference.v1.InferenceService/GetInferenceRequest", "safe"],
	["/mindclade.internal.inference.v1.InferenceService/GetInferenceResult", "safe"],
	["/mindclade.internal.inference.v1.InferenceService/CommitInferenceResult", "idempotent"],
	["/mindclade.internal.inference.v1.InferenceService/WatchInference", "safe"],
	["/mindclade.internal.evaluation.v1.EvaluationService/CreateEvaluationRun", "idempotent"],
	["/mindclade.internal.evaluation.v1.EvaluationService/GetEvaluationRun", "safe"],
	["/mindclade.internal.evaluation.v1.EvaluationService/ListEvaluationRuns", "safe"],
	["/mindclade.internal.evaluation.v1.EvaluationService/CancelEvaluationRun", "idempotent"],
	["/mindclade.internal.evaluation.v1.EvaluationService/CommitEvaluationResult", "idempotent"],
	["/mindclade.internal.evaluation.v1.EvaluationService/GetEvaluationResult", "safe"],
	["/mindclade.internal.evaluation.v1.EvaluationService/CreatePromotionDecision", "idempotent"],
	["/mindclade.internal.evaluation.v1.EvaluationService/GetPromotionDecision", "safe"],
	["/mindclade.internal.policy.v1.PolicyService/EvaluateAuthorization", "idempotent"],
	["/mindclade.internal.policy.v1.PolicyService/CreateUsePolicy", "idempotent"],
	["/mindclade.internal.policy.v1.PolicyService/UpdateUsePolicy", "idempotent"],
	["/mindclade.internal.policy.v1.PolicyService/GetUsePolicy", "safe"],
	["/mindclade.internal.policy.v1.PolicyService/ListUsePolicies", "safe"],
	["/mindclade.internal.policy.v1.PolicyService/ActivateUsePolicy", "idempotent"],
	["/mindclade.internal.policy.v1.PolicyService/RevokeUsePolicy", "idempotent"],
	["/mindclade.internal.policy.v1.PolicyService/ResolvePolicySnapshot", "safe"],
	["/mindclade.internal.admin.v1.AdminService/GetTenant", "safe"],
	["/mindclade.internal.admin.v1.AdminService/UpdateTenant", "idempotent"],
	["/mindclade.internal.admin.v1.AdminService/CreateProject", "idempotent"],
	["/mindclade.internal.admin.v1.AdminService/GetProject", "safe"],
	["/mindclade.internal.admin.v1.AdminService/ListProjects", "safe"],
	["/mindclade.internal.admin.v1.AdminService/UpdateProject", "idempotent"],
	["/mindclade.internal.admin.v1.AdminService/QueryAuditRecords", "safe"],
	["/mindclade.internal.admin.v1.AdminService/ExportAuditRecords", "idempotent"],
	["/mindclade.internal.admin.v1.AdminService/GetAuditExport", "safe"],
	["/mindclade.internal.agent.v1.AgentService/CreateAgentDefinition", "idempotent"],
	["/mindclade.internal.agent.v1.AgentService/UpdateAgentDefinition", "idempotent"],
	["/mindclade.internal.agent.v1.AgentService/GetAgentDefinition", "safe"],
	["/mindclade.internal.agent.v1.AgentService/ListAgentDefinitions", "safe"],
	["/mindclade.internal.agent.v1.AgentService/StartAgentRun", "idempotent"],
	["/mindclade.internal.agent.v1.AgentService/GetAgentRun", "safe"],
	["/mindclade.internal.agent.v1.AgentService/ListAgentRuns", "safe"],
	["/mindclade.internal.agent.v1.AgentService/CancelAgentRun", "idempotent"],
	["/mindclade.internal.agent.v1.AgentService/GetAgentStep", "safe"],
	["/mindclade.internal.agent.v1.AgentService/ListAgentSteps", "safe"],
	["/mindclade.internal.agent.v1.AgentService/CommitAgentStep", "idempotent"],
	["/mindclade.internal.agent.v1.AgentService/CommitToolReceipt", "idempotent"],
	["/mindclade.internal.workflow.v1.WorkflowService/CreateWorkflowDefinition", "idempotent"],
	["/mindclade.internal.workflow.v1.WorkflowService/UpdateWorkflowDefinition", "idempotent"],
	["/mindclade.internal.workflow.v1.WorkflowService/GetWorkflowDefinition", "safe"],
	["/mindclade.internal.workflow.v1.WorkflowService/ListWorkflowDefinitions", "safe"],
	["/mindclade.internal.workflow.v1.WorkflowService/StartWorkflowRun", "idempotent"],
	["/mindclade.internal.workflow.v1.WorkflowService/GetWorkflowRun", "safe"],
	["/mindclade.internal.workflow.v1.WorkflowService/ListWorkflowRuns", "safe"],
	["/mindclade.internal.workflow.v1.WorkflowService/CancelWorkflowRun", "idempotent"],
	["/mindclade.internal.workflow.v1.WorkflowService/CommitWorkflowTransition", "idempotent"],
	["/mindclade.internal.workflow.v1.WorkflowService/WatchWorkflowRun", "safe"],
	["/mindclade.internal.workflow.v1.ApprovalService/RequestApproval", "idempotent"],
	["/mindclade.internal.workflow.v1.ApprovalService/GetApprovalRequest", "safe"],
	["/mindclade.internal.workflow.v1.ApprovalService/ListApprovalRequests", "safe"],
	["/mindclade.internal.workflow.v1.ApprovalService/DecideApproval", "idempotent"],
	["/mindclade.internal.workflow.v1.ApprovalService/ConsumeApproval", "idempotent"],
]);

/** Unknown methods are unsafe and therefore receive exactly one attempt. */
export const registeredMethodSafety = (method: string): RetrySafety =>
	policies.get(method) ?? "unsafe";
