load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "bytes",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "mindclade_bytes",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = ["@crate_index//:sha2"],
)

filegroup(
    name = "governed_sources",
    srcs = ["BUILD.bazel"] + glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)
