# Copyright (c) 2026 Mindclade, LLC. All Rights Reserved.
# Mindclade Proprietary and Confidential.
# SPDX-License-Identifier: LicenseRef-Mindclade-Proprietary

"""Declarative integration contract for Pairformer transition."""

from kernels.api import (
    AutogradPolicy, CapabilityEnvelope, CompositeAutogradSpec, DeviceRef,
    DimensionConstraint, DimRef, DTypeRef, EffectSpec, Eq, ForwardSpec,
    GradientSpec, ImplementationSpec, ImplementationTier, IntLiteral,
    KernelSpec, LaunchContract, DeterminismClass, OutputSpec, ShapeTuple,
    TensorCapabilityConstraint,
)

KERNEL_SPEC = KernelSpec(
    name="transition", namespace="mindclade", family="pairformer",
    source="pairformer/transition/spec.py",
    operator_schema="transition(Tensor gate, Tensor value, Tensor output_weight, Tensor output_bias, Tensor mask) -> Tensor output",
    facade_outputs=("output",), fake=None,
    forward=ForwardSpec(
        schema="_transition_fwd(Tensor gate, Tensor value, Tensor output_weight, Tensor output_bias, Tensor mask) -> Tensor output",
        builder="kernels.pairformer.transition.tilelang:build_tilelang_program",
        symbol="mindclade_tilelang_transition_fwd_launch",
        outputs=(OutputSpec(
            name="output", shape=ShapeTuple(dimensions=(
                DimRef(argument="gate", axis=0),
                DimRef(argument="gate", axis=1),
                DimRef(argument="output_weight", axis=1),
            )),
            dtype=DTypeRef(argument="gate"), device=DeviceRef(argument="gate"),
            semantic_axes=("batch", "row", "channel"), visible_in_facade=True, saved_for_backward=False,
        ),),
    ),
    backward=None, autograd_policy=AutogradPolicy.COMPOSITE,
    composite=CompositeAutogradSpec(
        decomposition="kernels.pairformer.transition.reference:transition_reference",
        source_digest="sha256:66ee4727de452b204913aea9afedf38efaf7b744c18d7eaa3bc4d723454a49a2", runtime_envelope="pytorch>=2.10,<2.11",
        gradients=(
            GradientSpec(input_name="gate", output_name="grad_gate"),
            GradientSpec(input_name="value", output_name="grad_value"),
            GradientSpec(input_name="output_weight", output_name="grad_output_weight"),
            GradientSpec(input_name="output_bias", output_name="grad_output_bias"),
        ),
        supports_double_backward=False,
        setup_context="kernels.pairformer.transition.reference:setup_context",
        backward="kernels.pairformer.transition.reference:composite_backward",
    ),
    effects=EffectSpec(),
    launch=LaunchContract(graph_capture_safe=False, determinism=DeterminismClass.CONDITIONALLY_DETERMINISTIC),
)

IMPLEMENTATION_SPECS = (
    ImplementationSpec(
        operation="mindclade::transition",
        name="transition_sm90_pair_b1_r147456_h512_c128_bf16",
        family="pairformer",
        backend="tilelang",
        builder="kernels.pairformer.transition.tilelang:build_tilelang_program",
        version=1,
        tier=ImplementationTier.SPECIALIZED,
        requires=("cuda", "sm90a", "tilelang-0.1.13", "wgmma"),
        envelope=CapabilityEnvelope(
            architectures=("sm90a",),
            dtypes=("bfloat16",),
            layouts=("contiguous",),
            modes=("pair_b1_r147456_h512_c128_bf16",),
            constraints=(
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="gate", axis=0), rhs=IntLiteral(value=1)),
                    code="GATE_BATCH_EXACT", message="gate batch dimension must equal 1",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="gate", axis=1), rhs=IntLiteral(value=147456)),
                    code="GATE_ROWS_EXACT", message="gate row dimension must equal 147456",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="gate", axis=2), rhs=IntLiteral(value=512)),
                    code="GATE_HIDDEN_EXACT", message="gate hidden dimension must equal 512",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="value", axis=0), rhs=DimRef(argument="gate", axis=0)),
                    code="VALUE_BATCH_MATCH", message="value batch dimension must match gate",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="value", axis=1), rhs=DimRef(argument="gate", axis=1)),
                    code="VALUE_ROWS_MATCH", message="value row dimension must match gate",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="value", axis=2), rhs=DimRef(argument="gate", axis=2)),
                    code="VALUE_HIDDEN_MATCH", message="value hidden dimension must match gate",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="output_weight", axis=0), rhs=DimRef(argument="gate", axis=2)),
                    code="WEIGHT_HIDDEN_MATCH", message="output weight hidden dimension must match gate",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="output_weight", axis=1), rhs=IntLiteral(value=128)),
                    code="WEIGHT_CHANNELS_EXACT", message="output weight channel dimension must equal 128",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="output_bias", axis=0), rhs=DimRef(argument="output_weight", axis=1)),
                    code="BIAS_CHANNELS_MATCH", message="output bias channels must match output weight",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="mask", axis=0), rhs=DimRef(argument="gate", axis=0)),
                    code="MASK_BATCH_MATCH", message="mask batch dimension must match gate",
                ),
                DimensionConstraint(
                    predicate=Eq(lhs=DimRef(argument="mask", axis=1), rhs=DimRef(argument="gate", axis=1)),
                    code="MASK_ROWS_MATCH", message="mask row dimension must match gate",
                ),
            ),
            graph_capture_safe=False,
            training_capable=False,
            tensor_constraints=(
                TensorCapabilityConstraint(argument="gate", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="value", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="output_weight", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
                TensorCapabilityConstraint(argument="output_bias", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(1,)),
                TensorCapabilityConstraint(argument="mask", dtypes=("float32",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
            ),
        ),
        priority=0,
    ),
    ImplementationSpec(
        operation="mindclade::transition",
        name="transition_sm90_single_b1_r768_h1536_c384_bf16",
        family="pairformer",
        backend="tilelang",
        builder="kernels.pairformer.transition.tilelang:build_tilelang_program",
        version=1,
        tier=ImplementationTier.SPECIALIZED,
        requires=("cuda", "sm90a", "tilelang-0.1.13", "wgmma"),
        envelope=CapabilityEnvelope(
            architectures=("sm90a",),
            dtypes=("bfloat16",),
            layouts=("contiguous",),
            modes=("single_b1_r768_h1536_c384_bf16",),
            constraints=(
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=0), rhs=IntLiteral(value=1)), code="GATE_BATCH_EXACT", message="gate batch dimension must equal 1"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=1), rhs=IntLiteral(value=768)), code="GATE_ROWS_EXACT", message="gate row dimension must equal 768"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=2), rhs=IntLiteral(value=1536)), code="GATE_HIDDEN_EXACT", message="gate hidden dimension must equal 1536"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=0), rhs=DimRef(argument="gate", axis=0)), code="VALUE_BATCH_MATCH", message="value batch dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=1), rhs=DimRef(argument="gate", axis=1)), code="VALUE_ROWS_MATCH", message="value row dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=2), rhs=DimRef(argument="gate", axis=2)), code="VALUE_HIDDEN_MATCH", message="value hidden dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_weight", axis=0), rhs=DimRef(argument="gate", axis=2)), code="WEIGHT_HIDDEN_MATCH", message="output weight hidden dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_weight", axis=1), rhs=IntLiteral(value=384)), code="WEIGHT_CHANNELS_EXACT", message="output weight channel dimension must equal 384"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_bias", axis=0), rhs=DimRef(argument="output_weight", axis=1)), code="BIAS_CHANNELS_MATCH", message="output bias channels must match output weight"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="mask", axis=0), rhs=DimRef(argument="gate", axis=0)), code="MASK_BATCH_MATCH", message="mask batch dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="mask", axis=1), rhs=DimRef(argument="gate", axis=1)), code="MASK_ROWS_MATCH", message="mask row dimension must match gate"),
            ),
            graph_capture_safe=False,
            training_capable=False,
            tensor_constraints=(
                TensorCapabilityConstraint(argument="gate", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="value", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="output_weight", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
                TensorCapabilityConstraint(argument="output_bias", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(1,)),
                TensorCapabilityConstraint(argument="mask", dtypes=("float32",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
            ),
        ),
        priority=0,
    ),
    ImplementationSpec(
        operation="mindclade::transition",
        name="transition_sm100_pair_b1_r147456_h512_c128_bf16",
        family="pairformer",
        backend="tilelang",
        builder="kernels.pairformer.transition.tilelang:build_tilelang_program",
        version=1,
        tier=ImplementationTier.SPECIALIZED,
        requires=("cuda", "sm100a", "tilelang-0.1.13", "tcgen05"),
        envelope=CapabilityEnvelope(
            architectures=("sm100a",),
            dtypes=("bfloat16",),
            layouts=("contiguous",),
            modes=("pair_b1_r147456_h512_c128_bf16",),
            constraints=(
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=0), rhs=IntLiteral(value=1)), code="GATE_BATCH_EXACT", message="gate batch dimension must equal 1"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=1), rhs=IntLiteral(value=147456)), code="GATE_ROWS_EXACT", message="gate row dimension must equal 147456"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=2), rhs=IntLiteral(value=512)), code="GATE_HIDDEN_EXACT", message="gate hidden dimension must equal 512"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=0), rhs=DimRef(argument="gate", axis=0)), code="VALUE_BATCH_MATCH", message="value batch dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=1), rhs=DimRef(argument="gate", axis=1)), code="VALUE_ROWS_MATCH", message="value row dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=2), rhs=DimRef(argument="gate", axis=2)), code="VALUE_HIDDEN_MATCH", message="value hidden dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_weight", axis=0), rhs=DimRef(argument="gate", axis=2)), code="WEIGHT_HIDDEN_MATCH", message="output weight hidden dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_weight", axis=1), rhs=IntLiteral(value=128)), code="WEIGHT_CHANNELS_EXACT", message="output weight channel dimension must equal 128"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_bias", axis=0), rhs=DimRef(argument="output_weight", axis=1)), code="BIAS_CHANNELS_MATCH", message="output bias channels must match output weight"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="mask", axis=0), rhs=DimRef(argument="gate", axis=0)), code="MASK_BATCH_MATCH", message="mask batch dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="mask", axis=1), rhs=DimRef(argument="gate", axis=1)), code="MASK_ROWS_MATCH", message="mask row dimension must match gate"),
            ),
            graph_capture_safe=False,
            training_capable=False,
            tensor_constraints=(
                TensorCapabilityConstraint(argument="gate", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="value", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="output_weight", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
                TensorCapabilityConstraint(argument="output_bias", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(1,)),
                TensorCapabilityConstraint(argument="mask", dtypes=("float32",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
            ),
        ),
        priority=0,
    ),
    ImplementationSpec(
        operation="mindclade::transition",
        name="transition_sm100_single_b1_r768_h1536_c384_bf16",
        family="pairformer",
        backend="tilelang",
        builder="kernels.pairformer.transition.tilelang:build_tilelang_program",
        version=1,
        tier=ImplementationTier.SPECIALIZED,
        requires=("cuda", "sm100a", "tilelang-0.1.13", "tcgen05"),
        envelope=CapabilityEnvelope(
            architectures=("sm100a",),
            dtypes=("bfloat16",),
            layouts=("contiguous",),
            modes=("single_b1_r768_h1536_c384_bf16",),
            constraints=(
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=0), rhs=IntLiteral(value=1)), code="GATE_BATCH_EXACT", message="gate batch dimension must equal 1"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=1), rhs=IntLiteral(value=768)), code="GATE_ROWS_EXACT", message="gate row dimension must equal 768"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="gate", axis=2), rhs=IntLiteral(value=1536)), code="GATE_HIDDEN_EXACT", message="gate hidden dimension must equal 1536"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=0), rhs=DimRef(argument="gate", axis=0)), code="VALUE_BATCH_MATCH", message="value batch dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=1), rhs=DimRef(argument="gate", axis=1)), code="VALUE_ROWS_MATCH", message="value row dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="value", axis=2), rhs=DimRef(argument="gate", axis=2)), code="VALUE_HIDDEN_MATCH", message="value hidden dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_weight", axis=0), rhs=DimRef(argument="gate", axis=2)), code="WEIGHT_HIDDEN_MATCH", message="output weight hidden dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_weight", axis=1), rhs=IntLiteral(value=384)), code="WEIGHT_CHANNELS_EXACT", message="output weight channel dimension must equal 384"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="output_bias", axis=0), rhs=DimRef(argument="output_weight", axis=1)), code="BIAS_CHANNELS_MATCH", message="output bias channels must match output weight"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="mask", axis=0), rhs=DimRef(argument="gate", axis=0)), code="MASK_BATCH_MATCH", message="mask batch dimension must match gate"),
                DimensionConstraint(predicate=Eq(lhs=DimRef(argument="mask", axis=1), rhs=DimRef(argument="gate", axis=1)), code="MASK_ROWS_MATCH", message="mask row dimension must match gate"),
            ),
            graph_capture_safe=False,
            training_capable=False,
            tensor_constraints=(
                TensorCapabilityConstraint(argument="gate", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="value", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(3,)),
                TensorCapabilityConstraint(argument="output_weight", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
                TensorCapabilityConstraint(argument="output_bias", dtypes=("bfloat16",), layouts=("contiguous",), devices=("cuda",), ranks=(1,)),
                TensorCapabilityConstraint(argument="mask", dtypes=("float32",), layouts=("contiguous",), devices=("cuda",), ranks=(2,)),
            ),
        ),
        priority=0,
    ),
)
