// Code generated by tools/codegen/generate_cross_field_constraints.py. DO NOT EDIT.
// Source: protocols/constraints/cross-field.yaml
// Descriptor: sha256:f9a9dfd1eb8cbc6960f8f7e59f2dc5ec6191b7104e07ac9614db20945ffccccd

//! Cross-field constraints, generated from the governed table.
//!
//! Prost exposes no runtime reflection, so this module carries the rule table
//! and a presence-slice checker rather than a message walker. The caller
//! supplies which declared paths are set on the message it holds; the rule
//! arithmetic -- the part that must not differ between languages -- lives here.

use core::fmt;

/// One unsatisfied cross-field constraint.
///
/// `constraint` is the same identifier every other language reports, so a
/// facade error and a server error name the same rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CrossFieldError {
    pub constraint: &'static str,
    pub message: &'static str,
    pub rule: &'static str,
    pub fields: Vec<&'static str>,
}

impl fmt::Display for CrossFieldError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "{}: {} on {}: {}",
            self.constraint,
            self.rule,
            self.message,
            self.fields.join(", ")
        )
    }
}

impl std::error::Error for CrossFieldError {}

/// One generated rule.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CrossFieldRule {
    pub constraint: &'static str,
    pub message: &'static str,
    pub rule: &'static str,
    pub fields: &'static [&'static str],
}

/// The generated projection of `protocols/constraints/cross-field.yaml`.
/// Nothing may add to it by hand: a rule present in one language and absent
/// in another is the failure this table exists to prevent.
pub const CROSS_FIELD_RULES: [CrossFieldRule; 5] = [
    CrossFieldRule {
        constraint: "agent-definition-create-rejects-output-only-fields",
        message: "mindclade.internal.agent.v1.CreateAgentDefinitionRequest",
        rule: "output-only",
        fields: &[
            "agent_definition.name",
            "agent_definition.uid",
            "agent_definition.revision",
            "agent_definition.etag",
            "agent_definition.tenant_id",
            "agent_definition.project_id",
            "agent_definition.create_time",
            "agent_definition.update_time",
            "agent_definition.delete_time",
        ],
    },
    CrossFieldRule {
        constraint: "approval-request-create-rejects-output-only-fields",
        message: "mindclade.internal.workflow.v1.RequestApprovalRequest",
        rule: "output-only",
        fields: &[
            "approval_request.name",
            "approval_request.uid",
            "approval_request.revision",
            "approval_request.etag",
            "approval_request.tenant_id",
            "approval_request.project_id",
            "approval_request.requested_at",
        ],
    },
    CrossFieldRule {
        constraint: "project-create-rejects-output-only-fields",
        message: "mindclade.internal.admin.v1.CreateProjectRequest",
        rule: "output-only",
        fields: &[
            "project.name",
            "project.uid",
            "project.revision",
            "project.etag",
            "project.create_time",
            "project.update_time",
            "project.delete_time",
        ],
    },
    CrossFieldRule {
        constraint: "use-policy-create-rejects-output-only-fields",
        message: "mindclade.internal.policy.v1.CreateUsePolicyRequest",
        rule: "output-only",
        fields: &[
            "use_policy.name",
            "use_policy.uid",
            "use_policy.revision",
            "use_policy.etag",
            "use_policy.tenant_id",
            "use_policy.project_id",
            "use_policy.create_time",
            "use_policy.update_time",
            "use_policy.delete_time",
        ],
    },
    CrossFieldRule {
        constraint: "workflow-definition-create-rejects-output-only-fields",
        message: "mindclade.internal.workflow.v1.CreateWorkflowDefinitionRequest",
        rule: "output-only",
        fields: &[
            "workflow_definition.name",
            "workflow_definition.uid",
            "workflow_definition.revision",
            "workflow_definition.etag",
            "workflow_definition.tenant_id",
            "workflow_definition.project_id",
            "workflow_definition.create_time",
            "workflow_definition.update_time",
            "workflow_definition.delete_time",
        ],
    },
];

/// Return the rules declared for one fully qualified message name.
#[must_use]
pub fn rules_for(message: &str) -> Vec<CrossFieldRule> {
    CROSS_FIELD_RULES
        .iter()
        .filter(|rule| rule.message == message)
        .copied()
        .collect()
}

/// Evaluate one rule against the set of its declared paths that are populated.
///
/// `set` names paths from `rule.fields`; anything else is ignored, so a caller
/// cannot widen a rule by naming a path the table never declared.
///
/// # Errors
///
/// Returns [`CrossFieldError`] when the rule is not satisfied.
pub fn check(rule: CrossFieldRule, set: &[&str]) -> Result<(), CrossFieldError> {
    let present: Vec<&'static str> = rule
        .fields
        .iter()
        .copied()
        .filter(|field| set.contains(field))
        .collect();
    let total = rule.fields.len();
    let violated = match rule.rule {
        "output-only" => !present.is_empty(),
        "conflicts-with" => present.len() > 1,
        "xor-with" => present.len() != 1,
        "required-with" => !present.is_empty() && present.len() != total,
        _ => false,
    };
    if violated {
        let fields = if present.is_empty() {
            rule.fields.to_vec()
        } else {
            present
        };
        return Err(CrossFieldError {
            constraint: rule.constraint,
            message: rule.message,
            rule: rule.rule,
            fields,
        });
    }
    Ok(())
}
