#!/usr/bin/env python3.12
"""Deterministically render committed Wave 1 language bindings and baselines."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path

GENERATOR = "mindclade-contract-codegen 1.0.0"
MESSAGE = re.compile(r"^message\s+(?P<name>[A-Za-z][A-Za-z0-9_]*)\s*\{")
FIELD = re.compile(r"^(?P<type>[A-Za-z0-9_.]+)\s+(?P<name>[a-z][a-z0-9_]*)\s*=\s*\d+")
PACKAGE = re.compile(r"^package\s+(?P<name>[a-z0-9.]+);")


def sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def snake_to_pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.split("_"))


def parse_proto(path: Path) -> tuple[str, list[tuple[str, list[tuple[str, str]]]]]:
    package = ""
    messages: list[tuple[str, list[tuple[str, str]]]] = []
    active: tuple[str, list[tuple[str, str]]] | None = None
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if match := PACKAGE.match(line):
            package = match.group("name")
        elif match := MESSAGE.match(line):
            active = (match.group("name"), [])
            messages.append(active)
        elif line == "}":
            active = None
        elif active is not None and (match := FIELD.match(line)):
            active[1].append((match.group("type"), match.group("name")))
    if not package:
        raise ValueError(f"missing package declaration: {path}")
    return package, messages


def contracts(
    root: Path,
) -> dict[str, list[tuple[str, str, list[tuple[str, list[tuple[str, str]]]]]]]:
    grouped: dict[str, list[tuple[str, str, list[tuple[str, list[tuple[str, str]]]]]]] = (
        defaultdict(list)
    )
    for source in sorted((root / "protocols").glob("**/*.proto")):
        package, messages = parse_proto(source)
        domain = package.split(".")[-2]
        grouped[domain].append((source.stem, package, messages))
    return dict(sorted(grouped.items()))


def header(prefix: str) -> str:
    return f"{prefix} Code generated by {GENERATOR}; DO NOT EDIT.\n"


def render_go(package: str, messages: list[tuple[str, list[tuple[str, str]]]]) -> str:
    result = header("//") + "\npackage v1\n\n"
    for name, fields in messages:
        result += f"type {name} struct {{\n"
        for _, field in fields:
            result += f"\t{snake_to_pascal(field)} string\n"
        result += "}\n\n"
    return result.rstrip() + "\n"


def render_python(package: str, messages: list[tuple[str, list[tuple[str, str]]]]) -> str:
    result = header("#") + "\nfrom dataclasses import dataclass\n\n"
    for name, fields in messages:
        result += "@dataclass(frozen=True, slots=True)\n" + f"class {name}:\n"
        if fields:
            result += "\n".join(f'    {field}: str = ""' for _, field in fields) + "\n\n"
        else:
            result += "    pass\n\n"
    return result.rstrip() + "\n"


def render_rust(package: str, messages: list[tuple[str, list[tuple[str, str]]]]) -> str:
    result = header("//") + "\n"
    for name, fields in messages:
        result += "#[derive(Clone, Debug, Default, Eq, PartialEq)]\n" + f"pub struct {name} {{\n"
        for _, field in fields:
            result += f"    pub {field}: String,\n"
        result += "}\n\n"
    return result.rstrip() + "\n"


def render_typescript(package: str, messages: list[tuple[str, list[tuple[str, str]]]]) -> str:
    result = header("//") + "\n"
    for name, fields in messages:
        result += f"export interface {name} {{\n"
        for _, field in fields:
            result += f"  {field}: string;\n"
        result += "}\n\n"
    return result.rstrip() + "\n"


def generated_build(srcs: list[str], *, recursive_domains: bool = False) -> str:
    entries = "\n".join(f'        "{source}",' for source in srcs)
    recursive = ' + glob(["**/*"])' if recursive_domains else ""
    return (
        "# Code generated by mindclade-contract-codegen. DO NOT EDIT.\n\n"
        "filegroup(\n"
        '    name = "generated_sources",\n'
        f"    srcs = [\n{entries}\n    ]{recursive},\n"
        '    visibility = ["//visibility:public"],\n'
        ")\n"
    )


def rendered_files(root: Path) -> dict[Path, str]:
    output: dict[Path, str] = {}
    generated = root / "protocols" / "generated"
    package_contracts = contracts(root)
    for domain, sources in package_contracts.items():
        rust_modules: list[str] = []
        ts_exports: list[str] = []
        for stem, package, messages in sources:
            output[generated / "go" / domain / "v1" / f"{stem}.pb.go"] = render_go(
                package, messages
            )
            output[generated / "python" / domain / "v1" / f"{stem}_pb2.py"] = render_python(
                package, messages
            )
            output[generated / "rust" / domain / "v1" / f"{stem}.rs"] = render_rust(
                package, messages
            )
            output[generated / "typescript" / domain / "v1" / f"{stem}_pb.ts"] = render_typescript(
                package, messages
            )
            rust_modules.append(stem)
            ts_exports.append(f"export * from './{stem}_pb.js';")
        output[generated / "python" / domain / "v1" / "__init__.py"] = header("#")
        output[generated / "rust" / domain / "v1" / "mod.rs"] = (
            header("//") + "\n" + "\n".join(f"pub mod {module};" for module in rust_modules) + "\n"
        )
        output[generated / "typescript" / domain / "v1" / "index.ts"] = (
            header("//") + "\n" + "\n".join(ts_exports) + "\n"
        )
        output[generated / "go" / domain / "v1" / "BUILD.bazel"] = generated_build(
            ["BUILD.bazel"] + [f"{stem}.pb.go" for stem, _, _ in sources]
        )
    output[generated / "go" / "README.generated.md"] = (
        "# Generated Go bindings\n\nGenerated by the locked local contract generator.\n"
    )
    output[generated / "go" / "BUILD.bazel"] = generated_build(
        ["BUILD.bazel", "README.generated.md"]
        + [
            f"//protocols/generated/go/{domain}/v1:generated_sources"
            for domain in package_contracts
        ]
    )
    output[generated / "python" / "README.generated.md"] = (
        "# Generated Python bindings\n\nGenerated by the locked local contract generator.\n"
    )
    output[generated / "python" / "BUILD.bazel"] = generated_build([], recursive_domains=True)
    output[generated / "python" / "pyproject.toml"] = (
        "[project]\n"
        'name = "mindclade-generated-protocols"\n'
        'version = "0.1.0"\n'
        'requires-python = "==3.12.*"\n'
    )
    output[generated / "rust" / "README.generated.md"] = (
        "# Generated Rust bindings\n\nGenerated by the locked local contract generator.\n"
    )
    output[generated / "rust" / "BUILD.bazel"] = generated_build([], recursive_domains=True)
    output[generated / "rust" / "Cargo.toml"] = (
        "[package]\n"
        'name = "mindclade-protocols"\n'
        'version = "0.1.0"\n'
        'edition = "2024"\n'
        "publish = false\n\n"
        "[lib]\n"
        'path = "lib.rs"\n'
    )
    output[generated / "rust" / "lib.rs"] = (
        header("//")
        + "\n"
        + "\n".join(f"pub mod {domain} {{ pub mod v1; }}" for domain in package_contracts)
        + "\n"
    )
    output[generated / "typescript" / "README.generated.md"] = (
        "# Generated TypeScript bindings\n\nGenerated by the locked local contract generator.\n"
    )
    output[generated / "typescript" / "BUILD.bazel"] = generated_build([], recursive_domains=True)
    output[generated / "typescript" / "package.json"] = (
        '{"name":"@mindclade/protocols","version":"0.1.0","private":true,"type":"module"}\n'
    )
    output[generated / "typescript" / "tsconfig.json"] = (
        '{"compilerOptions":{"strict":true,"target":"ES2024"}}\n'
    )
    output[generated / "README.md"] = (
        "# Generated protocol bindings\n\nGenerated by the locked local contract generator.\n"
    )
    output[generated / "BUILD.bazel"] = generated_build(
        [
            "BUILD.bazel",
            "README.md",
            "generated-files.manifest.json",
            "//protocols/generated/go:generated_sources",
            "//protocols/generated/python:generated_sources",
            "//protocols/generated/rust:generated_sources",
            "//protocols/generated/typescript:generated_sources",
        ]
    )
    source_digests = {
        str(path.relative_to(root)): sha256(path)
        for path in sorted((root / "protocols").glob("**/*.proto"))
    }
    schema_digests = {
        str(path.relative_to(root)): sha256(path)
        for path in sorted((root / "protocols" / "schemas").glob("**/*.schema.json"))
    }
    output[root / "protocols" / "compatibility" / "baselines" / "protobuf.lock.json"] = (
        json.dumps(
            {"schema_version": "mindclade.protobuf-baseline/v1", "sources": source_digests},
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    )
    output[root / "protocols" / "compatibility" / "baselines" / "json-schema.lock.json"] = (
        json.dumps(
            {"schema_version": "mindclade.json-schema-baseline/v1", "sources": schema_digests},
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    )
    output[root / "protocols" / "compatibility" / "baselines" / "openapi.lock.json"] = (
        '{"schema_version":"mindclade.openapi-baseline/v1","sources":{}}\n'
    )
    manifest_entries = {
        str(path.relative_to(root)): "sha256:" + hashlib.sha256(content.encode()).hexdigest()
        for path, content in sorted(output.items())
        if "generated-files.manifest" not in str(path)
    }
    output[generated / "generated-files.manifest.json"] = (
        json.dumps(
            {"generator": GENERATOR, "files": manifest_entries},
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n"
    )
    return output


def write_generated(root: Path) -> None:
    output = rendered_files(root)
    generated_root = root / "protocols" / "generated"
    for path in sorted(generated_root.glob("**/*"), reverse=True):
        if path.is_file() and "__pycache__" not in path.parts and path not in output:
            path.unlink()
    for path, content in output.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    args = parser.parse_args()
    write_generated(args.root.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
