#!/usr/bin/env python3.12
"""Generate the cross-field constraint validators from one governed table.

Single-field validation belongs to each server validator. This generator owns
only the invariants that relate two or more sibling fields of one request,
because those are the ones no single field's check can hold -- and the ones
that were being hand-copied from service to service until the copies disagreed.

Every message and every field path in `protocols/constraints/cross-field.yaml`
is resolved against the committed candidate descriptor before a line is
emitted, and the file names the descriptor digest it was written against. A
contract change that renames or removes a field therefore breaks generation
loudly rather than leaving five validators checking a field that no longer
exists.

The generator writes formatted text and shells out to no formatter. That is
deliberate: `generate_protocols.py` pins its toolchain by exact version string,
which is right for a pipeline that produces the descriptor, and wrong for one
that produces five small tables. Nothing here needs a toolchain to be
reproducible, so nothing here pins one.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import sys
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

import yaml
from google.protobuf import descriptor_pb2
from jsonschema import Draft202012Validator

CONSTRAINTS = Path("protocols/constraints/cross-field.yaml")
CONSTRAINTS_SCHEMA = Path("protocols/constraints/cross-field.schema.json")
CANDIDATE = Path("protocols/compatibility/baselines/protobuf.candidate.json")
GENERATED_FILES = Path("protocols/generated/generated-files.manifest.json")

SCHEMA_VERSION = "mindclade.cross-field-constraints/v1"

TYPE_MESSAGE = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
LABEL_REPEATED = descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED

RULE_TEXT = {
    "output-only": "is assigned by the server and must not be set on this request",
    "conflicts-with": "may not be set together",
    "xor-with": "requires exactly one to be set",
    "required-with": "must be set together or not at all",
}

GO_SERVER = Path("services/control_plane/internal/platform/validation/cross_field.generated.go")
GO_FACADE = Path("internal/sdk/go/mindclade/cross_field.generated.go")
PYTHON_FACADE = Path("internal/sdk/python/mindclade_internal_sdk/cross_field_generated.py")
TYPESCRIPT_FACADE = Path("internal/sdk/typescript/src/crossField.generated.ts")
RUST_FACADE = Path("internal/sdk/rust/src/cross_field_generated.rs")

BANNER = (
    "Code generated by tools/codegen/generate_cross_field_constraints.py. DO NOT EDIT.\n"
    "Source: protocols/constraints/cross-field.yaml\n"
    "Descriptor: {digest}"
)


class GenerationError(RuntimeError):
    """A constraint table that the descriptor does not support."""


@dataclass(frozen=True)
class FieldPath:
    """One resolved dot path, with the presence test its leaf kind implies."""

    path: str
    segments: tuple[str, ...]
    leaf_kind: str  # "message" | "string" | "bytes" | "bool" | "numeric" | "enum"
    repeated: bool


@dataclass(frozen=True)
class Constraint:
    identifier: str
    message: str
    rule: str
    fields: tuple[FieldPath, ...]
    origin: str
    reason: str

    @property
    def sentence(self) -> str:
        return f"{self.identifier}: {RULE_TEXT[self.rule]}"


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise GenerationError(f"expected a JSON object: {path}")
    return cast(dict[str, Any], value)


def index_messages(
    file_set: descriptor_pb2.FileDescriptorSet,
) -> dict[str, descriptor_pb2.DescriptorProto]:
    messages: dict[str, descriptor_pb2.DescriptorProto] = {}

    def walk(prefix: str, nested: Iterable[descriptor_pb2.DescriptorProto]) -> None:
        for message in nested:
            full_name = f"{prefix}.{message.name}"
            messages[full_name] = message
            walk(full_name, message.nested_type)

    for file in file_set.file:
        walk(file.package, file.message_type)
    return messages


def descriptor_bytes(root: Path) -> bytes:
    """Return the committed descriptor, digest-checked against both manifests."""

    candidate = load_json(root / CANDIDATE)
    raw = base64.b64decode(cast(dict[str, Any], candidate["descriptor_set"])["base64"])
    digest = "sha256:" + hashlib.sha256(raw).hexdigest()
    declared = cast(dict[str, Any], candidate["descriptor_set"])["digest"]
    if declared != digest:
        raise GenerationError(
            f"candidate baseline declares {declared} but its bytes digest to {digest}"
        )
    generated = load_json(root / GENERATED_FILES)["descriptor_digest"]
    if generated != digest:
        raise GenerationError(
            f"generated-files manifest declares {generated}, candidate baseline is {digest}"
        )
    return raw


def leaf_kind(field: descriptor_pb2.FieldDescriptorProto) -> str:
    proto = descriptor_pb2.FieldDescriptorProto
    if field.type == TYPE_MESSAGE:
        return "message"
    if field.type == proto.TYPE_STRING:
        return "string"
    if field.type == proto.TYPE_BYTES:
        return "bytes"
    if field.type == proto.TYPE_BOOL:
        return "bool"
    if field.type == proto.TYPE_ENUM:
        return "enum"
    return "numeric"


def resolve_path(
    messages: Mapping[str, descriptor_pb2.DescriptorProto],
    message: str,
    path: str,
    *,
    constraint: str,
) -> FieldPath:
    """Walk one dot path, refusing anything the generated code cannot test."""

    segments = tuple(path.split("."))
    current = message
    field: descriptor_pb2.FieldDescriptorProto | None = None
    for index, segment in enumerate(segments):
        owner = messages.get(current)
        if owner is None:
            raise GenerationError(
                f"{constraint}: {current} is not a message in the descriptor"
                f" (resolving {message}.{path})"
            )
        field = next((candidate for candidate in owner.field if candidate.name == segment), None)
        if field is None:
            raise GenerationError(
                f"{constraint}: {current} has no field {segment!r} (resolving {message}.{path})"
            )
        if field.label == LABEL_REPEATED:
            raise GenerationError(
                f"{constraint}: {message}.{path} traverses repeated field {segment!r};"
                " repeated presence is a length, not a presence test"
            )
        if index < len(segments) - 1:
            if field.type != TYPE_MESSAGE:
                raise GenerationError(
                    f"{constraint}: {message}.{path} descends through non-message field {segment!r}"
                )
            current = field.type_name.lstrip(".")
    assert field is not None
    return FieldPath(
        path=path,
        segments=segments,
        leaf_kind=leaf_kind(field),
        repeated=False,
    )


def load_constraints(root: Path) -> tuple[list[Constraint], str]:
    document = cast(
        dict[str, Any], yaml.safe_load((root / CONSTRAINTS).read_text(encoding="utf-8"))
    )
    schema = load_json(root / CONSTRAINTS_SCHEMA)
    Draft202012Validator.check_schema(schema)
    validator = Draft202012Validator(schema)
    # jsonschema ships no annotations for iter_errors; the elements are
    # ValidationError, and only their `path` and `message` are read below.
    raw_errors: list[Any] = list(validator.iter_errors(document))  # pyright: ignore[reportUnknownMemberType]
    errors = sorted(raw_errors, key=lambda error: list(error.path))
    if errors:
        joined = "\n".join(f"  {list(error.path)}: {error.message}" for error in errors)
        raise GenerationError(f"{CONSTRAINTS} does not satisfy its schema:\n{joined}")

    raw = descriptor_bytes(root)
    file_set = descriptor_pb2.FileDescriptorSet()
    file_set.ParseFromString(raw)
    messages = index_messages(file_set)

    digest = "sha256:" + hashlib.sha256(raw).hexdigest()
    if document["descriptor_digest"] != digest:
        raise GenerationError(
            f"{CONSTRAINTS} was written against {document['descriptor_digest']};"
            f" the committed descriptor is {digest}"
        )

    constraints: list[Constraint] = []
    seen: set[str] = set()
    for entry in cast(Sequence[Mapping[str, Any]], document["constraints"]):
        identifier = str(entry["id"])
        if identifier in seen:
            raise GenerationError(f"duplicate constraint id {identifier!r}")
        seen.add(identifier)
        message = str(entry["message"])
        if message not in messages:
            raise GenerationError(f"{identifier}: {message} is not a message in the descriptor")
        fields = tuple(
            resolve_path(messages, message, str(path), constraint=identifier)
            for path in cast(Sequence[Any], entry["fields"])
        )
        constraints.append(
            Constraint(
                identifier=identifier,
                message=message,
                rule=str(entry["rule"]),
                fields=fields,
                origin=str(entry["origin"]),
                reason=" ".join(str(entry["reason"]).split()),
            )
        )
    constraints.sort(key=lambda constraint: constraint.identifier)
    return constraints, digest


# --------------------------------------------------------------------------
# Emitters. Each renders the same table; only the presence test differs, because
# only the message representation differs.
# --------------------------------------------------------------------------


def banner_lines(digest: str, prefix: str) -> list[str]:
    return [f"{prefix}{line}".rstrip() for line in BANNER.format(digest=digest).split("\n")]


def render_go(constraints: Sequence[Constraint], digest: str, *, package: str) -> str:
    lines = banner_lines(digest, "// ")
    lines += [
        "",
        f"package {package}",
        "",
        "import (",
        '\t"fmt"',
        '\t"strings"',
        "",
        '\t"google.golang.org/protobuf/proto"',
        '\t"google.golang.org/protobuf/reflect/protoreflect"',
        ")",
        "",
        "// CrossFieldError reports one unsatisfied constraint. The identifier is",
        "// the same string in every language, so an error raised by a facade and an",
        "// error raised by the server name the same rule.",
        "type CrossFieldError struct {",
        "\tConstraint string",
        "\tMessage    string",
        "\tRule       string",
        "\tFields     []string",
        "}",
        "",
        "func (v *CrossFieldError) Error() string {",
        "\treturn fmt.Sprintf(",
        '\t\t"%s: %s on %s: %s",',
        '\t\tv.Constraint, v.Rule, v.Message, strings.Join(v.Fields, ", "),',
        "\t)",
        "}",
        "",
        "type crossFieldRule struct {",
        "\tconstraint string",
        "\tmessage    string",
        "\trule       string",
        "\tfields     [][]string",
        "}",
        "",
        "// crossFieldRules is the generated projection of",
        "// protocols/constraints/cross-field.yaml. Nothing may add to it by hand:",
        "// a rule that exists in one language and not another is the failure this",
        "// table exists to prevent.",
        "var crossFieldRules = []crossFieldRule{",
    ]
    for constraint in constraints:
        lines += [
            "\t{",
            f'\t\tconstraint: "{constraint.identifier}",',
            f'\t\tmessage:    "{constraint.message}",',
            f'\t\trule:       "{constraint.rule}",',
            "\t\tfields: [][]string{",
        ]
        for field in constraint.fields:
            segments = ", ".join(f'"{segment}"' for segment in field.segments)
            lines.append(f"\t\t\t{{{segments}}},")
        lines += ["\t\t},", "\t},"]
    lines += [
        "}",
        "",
        "// fieldIsSet reports proto3 presence: a field is set when it is not its zero",
        "// value. A path that stops at an absent message is unset, not an error --",
        "// an unset parent cannot have a set child.",
        "func fieldIsSet(message proto.Message, path []string) bool {",
        "\tcurrent := message.ProtoReflect()",
        "\tfor index, name := range path {",
        "\t\tdescriptor := current.Descriptor().Fields().ByName(protoreflect.Name(name))",
        "\t\tif descriptor == nil {",
        "\t\t\treturn false",
        "\t\t}",
        "\t\tif index == len(path)-1 {",
        "\t\t\tif current.Has(descriptor) {",
        "\t\t\t\treturn true",
        "\t\t\t}",
        "\t\t\treturn !isZeroScalar(current.Get(descriptor), descriptor)",
        "\t\t}",
        "\t\tif !current.Has(descriptor) {",
        "\t\t\treturn false",
        "\t\t}",
        "\t\tcurrent = current.Get(descriptor).Message()",
        "\t}",
        "\treturn false",
        "}",
        "",
        "func isZeroScalar(",
        "\tvalue protoreflect.Value,",
        "\tdescriptor protoreflect.FieldDescriptor,",
        ") bool {",
        "\tif descriptor.Kind() == protoreflect.MessageKind ||",
        "\t\tdescriptor.Kind() == protoreflect.GroupKind {",
        "\t\treturn true",
        "\t}",
        "\treturn value.Equal(descriptor.Default())",
        "}",
        "",
        "// ValidateCrossField checks every constraint declared for this message type.",
        "// A message with no constraints passes; the caller need not know which types",
        "// carry rules.",
        "func ValidateCrossField(message proto.Message) error {",
        "\tif message == nil {",
        "\t\treturn nil",
        "\t}",
        "\tname := string(message.ProtoReflect().Descriptor().FullName())",
        "\tfor _, rule := range crossFieldRules {",
        "\t\tif rule.message != name {",
        "\t\t\tcontinue",
        "\t\t}",
        "\t\tset := make([]string, 0, len(rule.fields))",
        "\t\tfor _, path := range rule.fields {",
        "\t\t\tif fieldIsSet(message, path) {",
        '\t\t\t\tset = append(set, strings.Join(path, "."))',
        "\t\t\t}",
        "\t\t}",
        "\t\tif violated(rule.rule, len(set), len(rule.fields)) {",
        "\t\t\tfields := set",
        "\t\t\tif len(fields) == 0 {",
        "\t\t\t\tfields = joinedPaths(rule.fields)",
        "\t\t\t}",
        "\t\t\treturn &CrossFieldError{",
        "\t\t\t\tConstraint: rule.constraint,",
        "\t\t\t\tMessage:    rule.message,",
        "\t\t\t\tRule:       rule.rule,",
        "\t\t\t\tFields:     fields,",
        "\t\t\t}",
        "\t\t}",
        "\t}",
        "\treturn nil",
        "}",
        "",
        "func joinedPaths(paths [][]string) []string {",
        "\tjoined := make([]string, 0, len(paths))",
        "\tfor _, path := range paths {",
        '\t\tjoined = append(joined, strings.Join(path, "."))',
        "\t}",
        "\treturn joined",
        "}",
        "",
        "func violated(rule string, set, total int) bool {",
        "\tswitch rule {",
        '\tcase "output-only":',
        "\t\treturn set > 0",
        '\tcase "conflicts-with":',
        "\t\treturn set > 1",
        '\tcase "xor-with":',
        "\t\treturn set != 1",
        '\tcase "required-with":',
        "\t\treturn set != 0 && set != total",
        "\t}",
        "\treturn false",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_python(constraints: Sequence[Constraint], digest: str) -> str:
    lines = [f'"""{BANNER.format(digest=digest)}"""', ""]
    lines += [
        "from __future__ import annotations",
        "",
        "from typing import Any, Final",
        "",
        "",
        "class CrossFieldError(ValueError):",
        '    """One unsatisfied cross-field constraint.',
        "",
        "    ``constraint`` is the same identifier every other language reports, so a",
        "    facade error and a server error name the same rule.",
        '    """',
        "",
        "    def __init__("
        + "self, constraint: str, message: str, rule: str, fields: list[str]"
        + ") -> None:",
        "        super().__init__(f\"{constraint}: {rule} on {message}: {', '.join(fields)}\")",
        "        self.constraint = constraint",
        "        self.message_type = message",
        "        self.rule = rule",
        "        self.fields = fields",
        "",
        "",
        "# The generated projection of protocols/constraints/cross-field.yaml. Nothing",
        "# may add to it by hand: a rule present in one language and absent in another",
        "# is the failure this table exists to prevent.",
        "CrossFieldRule = tuple[str, str, str, tuple[tuple[str, ...], ...]]",
        "",
        "CROSS_FIELD_RULES: Final[tuple[CrossFieldRule, ...]] = (",
    ]
    for constraint in constraints:
        lines += [
            "    (",
            f'        "{constraint.identifier}",',
            f'        "{constraint.message}",',
            f'        "{constraint.rule}",',
            "        (",
        ]
        for field in constraint.fields:
            segments = ", ".join(f'"{segment}"' for segment in field.segments)
            if len(field.segments) == 1:
                segments += ","
            lines.append(f"            ({segments}),")
        lines += ["        ),", "    ),"]
    lines += [
        ")",
        "",
        "",
        "def _is_set(message: Any, path: tuple[str, ...]) -> bool:",
        '    """Proto3 presence: set means "not the zero value".',
        "",
        "    A path that stops at an absent message is unset rather than an error --",
        "    an unset parent cannot have a set child.",
        '    """',
        "",
        "    current: Any = message",
        "    for index, name in enumerate(path):",
        "        descriptor = current.DESCRIPTOR.fields_by_name.get(name)",
        "        if descriptor is None:",
        "            return False",
        "        if index == len(path) - 1:",
        "            if descriptor.message_type is not None:",
        "                return current.HasField(name)",
        "            return bool(getattr(current, name))",
        "        if not current.HasField(name):",
        "            return False",
        "        current = getattr(current, name)",
        "    return False",
        "",
        "",
        "def _violated(rule: str, count: int, total: int) -> bool:",
        '    if rule == "output-only":',
        "        return count > 0",
        '    if rule == "conflicts-with":',
        "        return count > 1",
        '    if rule == "xor-with":',
        "        return count != 1",
        '    if rule == "required-with":',
        "        return count not in (0, total)",
        "    return False",
        "",
        "",
        "def validate_cross_field(message: Any) -> None:",
        '    """Check every constraint declared for this message type.',
        "",
        "    A message with no constraints passes, so the caller need not know which",
        "    types carry rules.",
        '    """',
        "",
        "    if message is None:",
        "        return",
        "    name = message.DESCRIPTOR.full_name",
        "    for constraint, declared, rule, paths in CROSS_FIELD_RULES:",
        "        if declared != name:",
        "            continue",
        "        present = [_join(path) for path in paths if _is_set(message, path)]",
        "        if _violated(rule, len(present), len(paths)):",
        "            raise CrossFieldError(",
        "                constraint, declared, rule, present or [_join(path) for path in paths]",
        "            )",
        "",
        "",
        "def _join(path: tuple[str, ...]) -> str:",
        '    return ".".join(path)',
        "",
    ]
    return "\n".join(lines)


def camel(segment: str) -> str:
    """Field name as protobuf-es emits it.

    The descriptor names fields in snake_case and protobuf-es generates
    camelCase properties, so a TypeScript walker fed descriptor names finds
    nothing at all -- a validator that reports no violation on every message.
    """

    head, *rest = segment.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def render_typescript(constraints: Sequence[Constraint], digest: str) -> str:
    lines = banner_lines(digest, "// ")
    lines += [
        "",
        "/** One unsatisfied cross-field constraint.",
        " *",
        " * `constraint` is the same identifier every other language reports, so a",
        " * facade error and a server error name the same rule.",
        " */",
        "export class CrossFieldError extends Error {",
        "\treadonly constraint: string;",
        "\treadonly messageType: string;",
        "\treadonly rule: string;",
        "\treadonly fields: readonly string[];",
        "",
        "\tconstructor("
        + "constraint: string, messageType: string, "
        + "rule: string, fields: readonly string[]"
        + ") {",
        '\t\tsuper(`${constraint}: ${rule} on ${messageType}: ${fields.join(", ")}`);',
        '\t\tthis.name = "CrossFieldError";',
        "\t\tthis.constraint = constraint;",
        "\t\tthis.messageType = messageType;",
        "\t\tthis.rule = rule;",
        "\t\tthis.fields = fields;",
        "\t}",
        "}",
        "",
        "export interface CrossFieldRule {",
        "\treadonly constraint: string;",
        "\treadonly message: string;",
        "\treadonly rule: string;",
        "\treadonly fields: readonly (readonly string[])[];",
        "}",
        "",
        "// The generated projection of protocols/constraints/cross-field.yaml. Nothing",
        "// may add to it by hand: a rule present in one language and absent in another",
        "// is the failure this table exists to prevent.",
        "//",
        "// Paths are the camelCase names protobuf-es generates, not the snake_case the",
        "// descriptor declares -- a walker fed descriptor names finds nothing and",
        "// reports no violation on every message.",
        "export const CROSS_FIELD_RULES: readonly CrossFieldRule[] = [",
    ]
    for constraint in constraints:
        lines += [
            "\t{",
            f'\t\tconstraint: "{constraint.identifier}",',
            f'\t\tmessage: "{constraint.message}",',
            f'\t\trule: "{constraint.rule}",',
            "\t\tfields: [",
        ]
        for field in constraint.fields:
            segments = ", ".join(f'"{camel(segment)}"' for segment in field.segments)
            lines.append(f"\t\t\t[{segments}],")
        lines += ["\t\t],", "\t},"]
    lines += [
        "];",
        "",
        "// Proto3 presence: set means not the zero value. A path that stops at an",
        "// absent message is unset rather than an error.",
        "function isSet(message: unknown, path: readonly string[]): boolean {",
        "\tlet current: unknown = message;",
        "\tfor (const [index, segment] of path.entries()) {",
        "\t\tif (current === null || current === undefined) {",
        "\t\t\treturn false;",
        "\t\t}",
        '\t\tif (typeof current !== "object") {',
        "\t\t\treturn false;",
        "\t\t}",
        "\t\tconst value = (current as Record<string, unknown>)[segment];",
        "\t\tif (index === path.length - 1) {",
        "\t\t\tif (value === null || value === undefined) return false;",
        '\t\t\tif (typeof value === "string") return value.length > 0;',
        '\t\t\tif (typeof value === "number") return value !== 0;',
        '\t\t\tif (typeof value === "bigint") return value !== 0n;',
        '\t\t\tif (typeof value === "boolean") return value;',
        "\t\t\treturn true;",
        "\t\t}",
        "\t\tcurrent = value;",
        "\t}",
        "\treturn false;",
        "}",
        "",
        "function violated(rule: string, count: number, total: number): boolean {",
        "\tswitch (rule) {",
        '\t\tcase "output-only":',
        "\t\t\treturn count > 0;",
        '\t\tcase "conflicts-with":',
        "\t\t\treturn count > 1;",
        '\t\tcase "xor-with":',
        "\t\t\treturn count !== 1;",
        '\t\tcase "required-with":',
        "\t\t\treturn count !== 0 && count !== total;",
        "\t\tdefault:",
        "\t\t\treturn false;",
        "\t}",
        "}",
        "",
        "/** Check every constraint declared for `messageType`. */",
        "export function validateCrossField("
        + "messageType: string, message: unknown"
        + "): void {",
        "\tfor (const rule of CROSS_FIELD_RULES) {",
        "\t\tif (rule.message !== messageType) continue;",
        "\t\tconst present = rule.fields",
        "\t\t\t.filter((path) => isSet(message, path))",
        '\t\t\t.map((path) => path.join("."));',
        "\t\tif (violated(rule.rule, present.length, rule.fields.length)) {",
        "\t\t\tconst named = present.length > 0 ? present : "
        + 'rule.fields.map((path) => path.join("."));',
        "\t\t\tthrow new CrossFieldError("
        + "rule.constraint, rule.message, rule.rule, named"
        + ");",
        "\t\t}",
        "\t}",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_rust(constraints: Sequence[Constraint], digest: str) -> str:
    lines = banner_lines(digest, "// ")
    lines += [
        "",
        "//! Cross-field constraints, generated from the governed table.",
        "//!",
        "//! Prost exposes no runtime reflection, so this module carries the rule table",
        "//! and a presence-slice checker rather than a message walker. The caller",
        "//! supplies which declared paths are set on the message it holds; the rule",
        "//! arithmetic -- the part that must not differ between languages -- lives here.",
        "",
        "use core::fmt;",
        "",
        "/// One unsatisfied cross-field constraint.",
        "///",
        "/// `constraint` is the same identifier every other language reports, so a",
        "/// facade error and a server error name the same rule.",
        "#[derive(Debug, Clone, PartialEq, Eq)]",
        "pub struct CrossFieldError {",
        "    pub constraint: &'static str,",
        "    pub message: &'static str,",
        "    pub rule: &'static str,",
        "    pub fields: Vec<&'static str>,",
        "}",
        "",
        "impl fmt::Display for CrossFieldError {",
        "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
        "        write!(",
        "            formatter,",
        '            "{}: {} on {}: {}",',
        "            self.constraint,",
        "            self.rule,",
        "            self.message,",
        '            self.fields.join(", ")',
        "        )",
        "    }",
        "}",
        "",
        "impl std::error::Error for CrossFieldError {}",
        "",
        "/// One generated rule.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct CrossFieldRule {",
        "    pub constraint: &'static str,",
        "    pub message: &'static str,",
        "    pub rule: &'static str,",
        "    pub fields: &'static [&'static str],",
        "}",
        "",
        "/// The generated projection of `protocols/constraints/cross-field.yaml`.",
        "/// Nothing may add to it by hand: a rule present in one language and absent",
        "/// in another is the failure this table exists to prevent.",
        f"pub const CROSS_FIELD_RULES: [CrossFieldRule; {len(constraints)}] = [",
    ]
    for constraint in constraints:
        lines += [
            "    CrossFieldRule {",
            f'        constraint: "{constraint.identifier}",',
            f'        message: "{constraint.message}",',
            f'        rule: "{constraint.rule}",',
        ]
        # rustfmt keeps a list on one line while it fits, and explodes it when it
        # does not. Emitting the same shape keeps `cargo fmt --check` quiet
        # without this generator having to run a formatter.
        inline = ", ".join(f'"{field.path}"' for field in constraint.fields)
        if len(f"        fields: &[{inline}],") <= 100:
            lines.append(f"        fields: &[{inline}],")
        else:
            lines.append("        fields: &[")
            for field in constraint.fields:
                lines.append(f'            "{field.path}",')
            lines.append("        ],")
        lines.append("    },")
    lines += [
        "];",
        "",
        "/// Return the rules declared for one fully qualified message name.",
        "#[must_use]",
        "pub fn rules_for(message: &str) -> Vec<CrossFieldRule> {",
        "    CROSS_FIELD_RULES",
        "        .iter()",
        "        .filter(|rule| rule.message == message)",
        "        .copied()",
        "        .collect()",
        "}",
        "",
        "/// Evaluate one rule against the set of its declared paths that are populated.",
        "///",
        "/// `set` names paths from `rule.fields`; anything else is ignored, so a caller",
        "/// cannot widen a rule by naming a path the table never declared.",
        "///",
        "/// # Errors",
        "///",
        "/// Returns [`CrossFieldError`] when the rule is not satisfied.",
        "pub fn check(rule: CrossFieldRule, set: &[&str]) -> Result<(), CrossFieldError> {",
        "    let present: Vec<&'static str> = rule",
        "        .fields",
        "        .iter()",
        "        .copied()",
        "        .filter(|field| set.contains(field))",
        "        .collect();",
        "    let total = rule.fields.len();",
        "    let violated = match rule.rule {",
        '        "output-only" => !present.is_empty(),',
        '        "conflicts-with" => present.len() > 1,',
        '        "xor-with" => present.len() != 1,',
        '        "required-with" => !present.is_empty() && present.len() != total,',
        "        _ => false,",
        "    };",
        "    if violated {",
        "        let fields = if present.is_empty() {",
        "            rule.fields.to_vec()",
        "        } else {",
        "            present",
        "        };",
        "        return Err(CrossFieldError {",
        "            constraint: rule.constraint,",
        "            message: rule.message,",
        "            rule: rule.rule,",
        "            fields,",
        "        });",
        "    }",
        "    Ok(())",
        "}",
        "",
    ]
    return "\n".join(lines)


def outputs(constraints: Sequence[Constraint], digest: str) -> dict[Path, str]:
    return {
        GO_SERVER: render_go(constraints, digest, package="validation"),
        GO_FACADE: render_go(constraints, digest, package="mindclade"),
        PYTHON_FACADE: render_python(constraints, digest),
        TYPESCRIPT_FACADE: render_typescript(constraints, digest),
        RUST_FACADE: render_rust(constraints, digest),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a committed validator differs from what this table generates",
    )
    args = parser.parse_args(argv)
    root = args.root.resolve()

    try:
        constraints, digest = load_constraints(root)
    except GenerationError as error:
        print(f"cross-field constraints: {error}", file=sys.stderr)
        return 1

    stale: list[str] = []
    for relative, content in outputs(constraints, digest).items():
        path = root / relative
        if args.check:
            current = path.read_text(encoding="utf-8") if path.is_file() else ""
            if current != content:
                stale.append(relative.as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    if args.check:
        if stale:
            print("cross-field validators are stale:", file=sys.stderr)
            for relative in stale:
                print(f"  {relative}", file=sys.stderr)
            return 1
        print(f"cross-field validators are current ({len(constraints)} constraints)")
        return 0

    print(f"generated {len(constraints)} cross-field constraints into 5 languages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
