#!/usr/bin/env python3.12
"""Fail-closed planner for optional, non-authoritative REST SDK comparisons.

Native internal SDK transport is generated by Buf and the pinned
Protobuf/gRPC/Connect plugins. This tool never generates that transport. It
validates and plans optional Fern or Speakeasy HTTP/JSON comparisons only.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NoReturn, cast

import yaml

PLAN_SCHEMA_VERSION = "mindclade.optional-rest-sdk-plan/v4"
PROVENANCE_SCHEMA_VERSION = "mindclade.optional-rest-sdk-provenance/v3"
DEFAULT_OPENAPI = Path("protocols/openapi/published/mindclade.openapi.yaml")
DEFAULT_GENERATION = Path("protocols/openapi/generation.yaml")
OPTIONAL_POLICY_SOURCE = "protocols/openapi/generation.yaml#spec.optionalRestGeneration"
DEFAULT_PLAN = Path("optional-rest-sdk-plan.json")
HTTP_METHODS = frozenset({"delete", "get", "head", "options", "patch", "post", "put", "trace"})
INTERNAL_LANGUAGES = ("go", "python", "rust", "typescript")
OPTIONAL_LANGUAGES = INTERNAL_LANGUAGES
UNPINNED_VERSION = "unpinned"
EXIT_USAGE = 2
EXIT_CONNECTED_NOT_READY = 3
EXIT_VERIFY_MISMATCH = 4


class SdkGeneratorError(ValueError):
    """The optional REST contract is unsafe or inconsistent."""


class ConnectedGenerationError(RuntimeError):
    """Connected optional generation is not configured or authorized."""


@dataclass(frozen=True)
class ProviderAdapter:
    provider_id: str
    role: str
    languages: tuple[str, ...]


ADAPTERS: Mapping[str, ProviderAdapter] = {
    "fern": ProviderAdapter(
        "fern",
        "optional-internal-rest-generator",
        ("go", "python", "rust", "typescript"),
    ),
    "speakeasy": ProviderAdapter(
        "speakeasy",
        "optional-specialized-rest-benchmark",
        ("go", "python", "typescript"),
    ),
}

NATIVE_PIPELINE_INTERFACES = (
    "ProtoContractValidator",
    "BufNativeGenerator",
    "GeneratedBindingCompiler",
    "InternalFacadeBuilder",
    "InternalSdkConformanceVerifier",
    "LayeringPolicyVerifier",
)
OPTIONAL_PIPELINE_INTERFACES = (
    "OpenApiValidator",
    "ProviderPolicyCompiler",
    "SdkEmitter",
    "SdkBehaviorVerifier",
)
PRODUCTION_QUALITY: Mapping[str, frozenset[str]] = {
    "codegen": frozenset(
        {
            "atomic-staged-generation",
            "deterministic-two-pass-regeneration",
            "descriptor-digest-join-key",
            "generated-file-manifest",
            "four-language-compile-and-import",
            "descriptor-derived-rpc-coverage",
            "generated-and-handwritten-boundary",
            "fault-injection-with-rollback",
            "preview-diff-without-publication-authority",
            "package-inventory-and-provenance",
        }
    ),
    "runtime": frozenset(
        {
            "workload-identity-and-credential-refresh",
            "secure-transport-by-default",
            "bounded-deadlines-and-message-sizes",
            "safe-idempotent-retries-with-jitter-and-server-hints",
            "caller-stable-idempotency-and-request-ids",
            "sanitized-typed-errors",
            "opaque-bounded-pagination",
            "long-running-operation-poll-watch-and-cancel",
            "resumable-streaming-with-heartbeats",
            "verified-atomic-artifact-transfer",
            "cancellation-and-shutdown-propagation",
            "observers-fakes-and-hermetic-transports",
        }
    ),
    "testing": frozenset(
        {
            "every-rpc-four-language-behavioral-evidence",
            "populated-wire-and-protojson-roundtrips",
            "auth-timeout-retry-error-and-idempotency-conformance",
            "pagination-operation-and-stream-resume-conformance",
            "artifact-integrity-race-and-no-clobber-conformance",
            "generated-drift-and-layering-enforcement",
        }
    ),
    "lifecycle": frozenset(
        {
            "ergonomic-raw-only-or-unsupported-classification",
            "explicit-deprecation-and-migration-policy",
            "candidate-only-change-policy-before-ratification",
            "immutable-breaking-baseline-after-ratification",
        }
    ),
    "delivery": frozenset(
        {
            "private-package-inventories",
            "source-toolchain-and-contract-digests",
            "qualification-and-release-receipts",
            "no-public-package-publication",
        }
    ),
    "excludedOrDeferred": frozenset(
        {
            "hosted-generator-authority",
            "public-package-marketing-and-portal",
            "terraform-provider-generation",
            "websocket-transport-duplication",
            "webhook-runtime-without-a-signed-contract",
            "unbounded-mcp-surface-export",
        }
    ),
}


def sha256_bytes(value: bytes) -> str:
    return "sha256:" + hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def canonical_json(value: Mapping[str, Any]) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()


def load_yaml_mapping(path: Path) -> dict[str, Any]:
    try:
        value = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as error:
        raise SdkGeneratorError(f"cannot read {path}: {error}") from error
    if not isinstance(value, dict):
        raise SdkGeneratorError(f"{path} must contain a YAML mapping")
    return cast(dict[str, Any], value)


def require_mapping(value: Any, location: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise SdkGeneratorError(f"{location} must be a mapping")
    return cast(Mapping[str, Any], value)


def require_sequence(value: Any, location: str) -> Sequence[Any]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        raise SdkGeneratorError(f"{location} must be an array")
    return cast(Sequence[Any], value)


def require_string(value: Any, location: str) -> str:
    if not isinstance(value, str) or not value or "\n" in value or "\r" in value:
        raise SdkGeneratorError(f"{location} must be a non-empty single-line string")
    return value


def repository_root(openapi_path: Path) -> Path | None:
    for candidate in openapi_path.resolve().parents:
        if (candidate / "protocols/openapi").is_dir() and (candidate / "tools/codegen").is_dir():
            return candidate
    return None


def validate_output_root(output_root: Path, openapi_path: Path) -> Path:
    resolved = output_root.resolve()
    if resolved == Path(resolved.anchor):
        raise SdkGeneratorError("output root cannot be the filesystem root")
    repository = repository_root(openapi_path)
    if repository is not None and resolved == repository:
        raise SdkGeneratorError("output root cannot be the repository root")
    return resolved


def confined_output(output_root: Path, relative: Path, label: str) -> Path:
    if relative.is_absolute() or relative == Path() or ".." in relative.parts:
        raise SdkGeneratorError(f"{label} must be a non-empty relative path beneath output root")
    candidate = (output_root / relative).resolve()
    if candidate == output_root or not candidate.is_relative_to(output_root):
        raise SdkGeneratorError(f"{label} escapes output root: {relative}")
    return candidate


def write_atomic(output_root: Path, relative: Path, content: bytes) -> Path:
    destination = confined_output(output_root, relative, "output")
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.tmp")
    temporary.write_bytes(content)
    temporary.replace(destination)
    return destination


OPERATION_KINDS = frozenset({"unary", "server-stream", "sse"})
SSE_POLICY_FIELDS = frozenset(
    {
        "errorEventType",
        "eventModel",
        "heartbeatIntervalSeconds",
        "heartbeatReusesLastDurableEventId",
        "replayAcknowledgedTerminalEvent",
        "resumeHeader",
        "retryMilliseconds",
    }
)


def _positive_integer(value: Any, location: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise SdkGeneratorError(f"{location} must be a positive integer")
    return value


def operation_contracts(openapi: Mapping[str, Any]) -> tuple[dict[str, Any], ...]:
    """Validate operation-kind metadata so streams cannot become unary by omission."""

    paths = require_mapping(openapi.get("paths"), "OpenAPI paths")
    found: list[dict[str, Any]] = []
    for path_name, raw_path_item in paths.items():
        path_item = require_mapping(raw_path_item, f"OpenAPI path {path_name}")
        for method, raw_operation in path_item.items():
            if method not in HTTP_METHODS:
                continue
            operation = require_mapping(raw_operation, f"OpenAPI {method} {path_name}")
            operation_id = require_string(
                operation.get("operationId"),
                f"OpenAPI {method} {path_name}.operationId",
            )
            kind = require_string(
                operation.get("x-mindclade-operation-kind"),
                f"OpenAPI {method} {path_name}.x-mindclade-operation-kind",
            )
            if kind not in OPERATION_KINDS:
                raise SdkGeneratorError(
                    f"OpenAPI operation {operation_id} has unsupported operation kind {kind!r}"
                )
            raw_sse = operation.get("x-mindclade-sse")
            record: dict[str, Any] = {"kind": kind, "operationId": operation_id}
            if kind == "sse":
                sse = require_mapping(raw_sse, f"OpenAPI operation {operation_id} SSE policy")
                if set(sse) != set(SSE_POLICY_FIELDS):
                    raise SdkGeneratorError(
                        f"OpenAPI operation {operation_id} SSE policy fields differ"
                    )
                require_string(sse.get("eventModel"), f"{operation_id} SSE eventModel")
                if sse.get("errorEventType") != "error":
                    raise SdkGeneratorError(
                        f"OpenAPI operation {operation_id} SSE error event is unsupported"
                    )
                if sse.get("resumeHeader") != "Last-Event-ID":
                    raise SdkGeneratorError(
                        f"OpenAPI operation {operation_id} SSE resume header is unsupported"
                    )
                _positive_integer(sse.get("retryMilliseconds"), f"{operation_id} SSE retry")
                _positive_integer(
                    sse.get("heartbeatIntervalSeconds"), f"{operation_id} SSE heartbeat"
                )
                if sse.get("heartbeatReusesLastDurableEventId") is not True:
                    raise SdkGeneratorError(
                        f"OpenAPI operation {operation_id} SSE heartbeat policy is unsupported"
                    )
                if sse.get("replayAcknowledgedTerminalEvent") is not False:
                    raise SdkGeneratorError(
                        f"OpenAPI operation {operation_id} SSE terminal replay is unsupported"
                    )
                responses = require_mapping(
                    operation.get("responses"), f"OpenAPI operation {operation_id} responses"
                )
                success = require_mapping(
                    responses.get("200"), f"OpenAPI operation {operation_id} response 200"
                )
                content = require_mapping(
                    success.get("content"), f"OpenAPI operation {operation_id} response content"
                )
                if set(content) != {"text/event-stream"}:
                    raise SdkGeneratorError(
                        f"OpenAPI operation {operation_id} is not an explicit SSE response"
                    )
                record["ssePolicy"] = dict(sse)
            elif raw_sse is not None:
                raise SdkGeneratorError(
                    f"OpenAPI non-SSE operation {operation_id} declares SSE policy"
                )
            found.append(record)
    identifiers = [cast(str, record["operationId"]) for record in found]
    if not found or len(identifiers) != len(set(identifiers)):
        raise SdkGeneratorError("OpenAPI must contain unique, non-empty operationId values")
    return tuple(sorted(found, key=lambda record: cast(str, record["operationId"])))


def operation_ids(openapi: Mapping[str, Any]) -> tuple[str, ...]:
    return tuple(cast(str, record["operationId"]) for record in operation_contracts(openapi))


def operation_dispositions(
    optional: Mapping[str, Any],
    operations: Sequence[Mapping[str, Any]],
) -> dict[str, dict[str, str]]:
    """Require an explicit reviewed disposition for every non-unary operation."""

    policy = require_mapping(optional.get("streamingPolicy"), "streamingPolicy")
    if (
        policy.get("operationKindExtension") != "x-mindclade-operation-kind"
        or policy.get("ssePolicyExtension") != "x-mindclade-sse"
        or tuple(require_sequence(policy.get("eligibleKinds"), "streamingPolicy.eligibleKinds"))
        != ("unary",)
    ):
        raise SdkGeneratorError(
            "optional REST streaming policy must admit only explicitly classified unary methods"
        )
    reviewed = require_mapping(
        policy.get("reviewedUnsupported"), "streamingPolicy.reviewedUnsupported"
    )
    operation_by_id = {cast(str, operation["operationId"]): operation for operation in operations}
    dispositions: dict[str, dict[str, str]] = {}
    for operation_id, operation in operation_by_id.items():
        kind = cast(str, operation["kind"])
        raw_review = reviewed.get(operation_id)
        if kind == "unary":
            if raw_review is not None:
                raise SdkGeneratorError(
                    f"unary operation {operation_id} cannot be reviewed as unsupported"
                )
            dispositions[operation_id] = {"disposition": "eligible", "kind": kind}
            continue
        review = require_mapping(raw_review, f"streamingPolicy.reviewedUnsupported.{operation_id}")
        if set(review) != {"kind", "reason"} or review.get("kind") != kind:
            raise SdkGeneratorError(
                f"streaming operation {operation_id} has no exact reviewed disposition"
            )
        reason = require_string(
            review.get("reason"), f"streamingPolicy.reviewedUnsupported.{operation_id}.reason"
        )
        dispositions[operation_id] = {
            "disposition": "reviewed-unsupported",
            "kind": kind,
            "reason": reason,
        }
    unexpected = sorted(set(reviewed) - set(operation_by_id))
    if unexpected:
        raise SdkGeneratorError(f"streaming policy names unknown operations: {unexpected}")
    return dispositions


def public_schemas(openapi: Mapping[str, Any]) -> tuple[str, ...]:
    components = require_mapping(openapi.get("components"), "OpenAPI components")
    schemas = require_mapping(components.get("schemas"), "OpenAPI components.schemas")
    names = tuple(sorted(require_string(name, "OpenAPI schema name") for name in schemas))
    if not names:
        raise SdkGeneratorError("OpenAPI must declare public schemas")
    return names


def iter_local_refs(value: object) -> tuple[str, ...]:
    found: list[str] = []
    if isinstance(value, Mapping):
        for key, child in cast(Mapping[object, object], value).items():
            if key == "$ref":
                if not isinstance(child, str) or not child.startswith("#/"):
                    raise SdkGeneratorError(
                        f"OpenAPI references must be local JSON pointers: {child!r}"
                    )
                found.append(child)
            else:
                found.extend(iter_local_refs(child))
    elif isinstance(value, list):
        for child in cast(list[object], value):
            found.extend(iter_local_refs(child))
    return tuple(found)


def resolve_local_ref(document: Mapping[str, Any], reference: str) -> object:
    value: object = document
    for component in reference[2:].split("/"):
        component = component.replace("~1", "/").replace("~0", "~")
        if not isinstance(value, Mapping):
            raise SdkGeneratorError(f"unresolved OpenAPI reference: {reference}")
        mapping = cast(Mapping[str, object], value)
        if component not in mapping:
            raise SdkGeneratorError(f"unresolved OpenAPI reference: {reference}")
        value = mapping[component]
    return value


def configured_providers(
    optional: Mapping[str, Any],
) -> Mapping[str, Mapping[str, Any]]:
    providers: dict[str, Mapping[str, Any]] = {}
    for index, raw_provider in enumerate(
        require_sequence(optional.get("providers"), "optionalRestGeneration.providers")
    ):
        provider = require_mapping(raw_provider, f"providers[{index}]")
        provider_id = require_string(provider.get("id"), f"providers[{index}].id")
        if provider_id in providers:
            raise SdkGeneratorError(f"duplicate optional SDK provider: {provider_id}")
        providers[provider_id] = provider
    return providers


def validate_contract(
    openapi: Mapping[str, Any], generation: Mapping[str, Any]
) -> Mapping[str, Mapping[str, Any]]:
    if openapi.get("openapi") != "3.1.0":
        raise SdkGeneratorError("optional REST generation requires OpenAPI 3.1.0")
    for reference in iter_local_refs(openapi):
        resolve_local_ref(openapi, reference)
    operation_ids(openapi)
    public_schemas(openapi)

    if generation.get("kind") != "InternalSdkGeneration":
        raise SdkGeneratorError("generation kind must be InternalSdkGeneration")
    spec = require_mapping(generation.get("spec"), "generation.spec")
    authority = require_mapping(spec.get("authority"), "generation.spec.authority")
    if tuple(
        require_sequence(authority.get("contracts"), "generation.spec.authority.contracts")
    ) != ("protocols/proto", "protocols/events"):
        raise SdkGeneratorError("Protobuf proto/event sources must remain authoritative")
    if (
        authority.get("generatedRoot") != "protocols/generated"
        or authority.get("facadeRoot") != "sdks"
        or authority.get("generator") != "buf.gen.yaml"
    ):
        raise SdkGeneratorError("internal SDK direction must be protobuf -> generated -> sdks")

    native = require_mapping(spec.get("nativeGeneration"), "nativeGeneration")
    if native.get("implementation") != "buf-and-pinned-native-generators":
        raise SdkGeneratorError("Buf and pinned native generators must remain primary")
    languages = require_mapping(native.get("languages"), "nativeGeneration.languages")
    if tuple(languages) != INTERNAL_LANGUAGES:
        raise SdkGeneratorError("native generation languages must be go, python, rust, typescript")
    for language in INTERNAL_LANGUAGES:
        config = require_mapping(languages[language], f"nativeGeneration.{language}")
        if config.get("output") != f"protocols/generated/{language}":
            raise SdkGeneratorError(f"{language} generated output is not canonical")
        if config.get("facade") != f"sdks/{language}":
            raise SdkGeneratorError(f"{language} internal SDK facade is not canonical")

    pipeline = require_mapping(spec.get("pipeline"), "generation.spec.pipeline")
    if (
        tuple(require_sequence(pipeline.get("interfaces"), "generation.spec.pipeline.interfaces"))
        != NATIVE_PIPELINE_INTERFACES
    ):
        raise SdkGeneratorError("native internal SDK pipeline boundaries changed")

    policy = require_mapping(spec.get("internalSdkPolicy"), "internalSdkPolicy")
    if (
        policy.get("owner") != "mindclade"
        or policy.get("models") != "intentionally-exported-generated-protobuf-types"
        or policy.get("handwrittenWireModels") != "forbidden"
    ):
        raise SdkGeneratorError("internal SDK policy must reuse generated protobuf wire types")
    production_quality = require_mapping(
        policy.get("productionQuality"), "internalSdkPolicy.productionQuality"
    )
    if set(production_quality) != set(PRODUCTION_QUALITY):
        raise SdkGeneratorError("internal SDK production-quality categories changed")
    for category, expected in PRODUCTION_QUALITY.items():
        declared = tuple(
            require_string(value, f"internalSdkPolicy.productionQuality.{category} item")
            for value in require_sequence(
                production_quality.get(category),
                f"internalSdkPolicy.productionQuality.{category}",
            )
        )
        if len(declared) != len(set(declared)) or frozenset(declared) != expected:
            raise SdkGeneratorError(
                f"internal SDK production-quality contract differs for {category}"
            )

    optional = require_mapping(spec.get("optionalRestGeneration"), "optionalRestGeneration")
    if (
        optional.get("enabledByDefault") is not False
        or optional.get("authority") is not False
        or optional.get("policyOwner") != "mindclade"
        or optional.get("policySource") != OPTIONAL_POLICY_SOURCE
        or optional.get("providerConfigurationRule") != "derived-only"
    ):
        raise SdkGeneratorError(
            "optional REST providers must remain disabled, non-authoritative, and policy-derived"
        )
    if (
        tuple(require_sequence(optional.get("interfaces"), "optionalRestGeneration.interfaces"))
        != OPTIONAL_PIPELINE_INTERFACES
    ):
        raise SdkGeneratorError("optional REST provider interfaces changed")
    operation_dispositions(optional, operation_contracts(openapi))

    providers = configured_providers(optional)
    if set(providers) != set(ADAPTERS):
        raise SdkGeneratorError("optional REST providers must be exactly fern and speakeasy")
    for provider_id, adapter in ADAPTERS.items():
        provider = providers[provider_id]
        if provider.get("role") != adapter.role:
            raise SdkGeneratorError(f"{provider_id} role must be {adapter.role}")
        if (
            provider.get("foundational") is not False
            or provider.get("releasePrimaryEligible") is not False
        ):
            raise SdkGeneratorError(f"{provider_id} cannot be foundational or primary")
        if (
            tuple(require_sequence(provider.get("languages"), f"{provider_id}.languages"))
            != adapter.languages
        ):
            raise SdkGeneratorError(
                f"{provider_id} languages must be {', '.join(adapter.languages)}"
            )
        if provider.get("source") != DEFAULT_OPENAPI.as_posix():
            raise SdkGeneratorError(
                f"{provider_id} must consume only the curated OpenAPI projection"
            )
        configuration = require_mapping(
            provider.get("configuration"), f"{provider_id}.configuration"
        )
        if configuration.get("policySource") != OPTIONAL_POLICY_SOURCE:
            raise SdkGeneratorError(
                f"{provider_id} configuration must derive from Mindclade policy"
            )
        release = require_mapping(provider.get("release"), f"{provider_id}.release")
        if release.get("publish") is not False:
            raise SdkGeneratorError(f"{provider_id} publication must remain disabled")

    local = require_mapping(spec.get("localOptionalRestAdapter"), "localOptionalRestAdapter")
    if (
        local.get("implementation") != "tools/codegen/sdk_generator.py"
        or local.get("network") != "forbidden"
        or local.get("emitsSdkSource") is not False
    ):
        raise SdkGeneratorError(
            "local optional REST planner must be offline and emit no SDK source"
        )
    qualification = require_mapping(spec.get("qualification"), "qualification")
    if (
        qualification.get("optionalRestProviderRequired") is not False
        or qualification.get("publishAuthorized") is not False
    ):
        raise SdkGeneratorError("source policy cannot require a provider or authorize publication")
    return providers


def optional_policy_sha256(generation: Mapping[str, Any]) -> str:
    spec = require_mapping(generation.get("spec"), "generation.spec")
    optional = require_mapping(spec.get("optionalRestGeneration"), "optionalRestGeneration")
    return sha256_bytes(canonical_json(optional))


def selected_values(selection: str, available: Sequence[str]) -> tuple[str, ...]:
    return tuple(available) if selection == "all" else (selection,)


def selected_provider_languages(provider_id: str, language_selection: str) -> tuple[str, ...]:
    supported = ADAPTERS[provider_id].languages
    if language_selection == "all":
        return supported
    if language_selection not in supported:
        raise SdkGeneratorError(
            f"{provider_id} does not support configured language {language_selection}"
        )
    return (language_selection,)


def provider_version(provider: Mapping[str, Any], override: str | None) -> str:
    adapter = require_mapping(provider.get("adapter"), "provider.adapter")
    configured = require_string(adapter.get("providerVersion"), "provider.adapter.providerVersion")
    return configured if override is None else require_string(override, "provider version")


def build_plan(
    *,
    openapi_path: Path,
    generation_path: Path,
    output_root: Path,
    source_revision: str,
    provider_selection: str,
    language_selection: str,
    provider_version_override: str | None = None,
) -> dict[str, Any]:
    openapi = load_yaml_mapping(openapi_path)
    generation = load_yaml_mapping(generation_path)
    providers = validate_contract(openapi, generation)
    safe_root = validate_output_root(output_root, openapi_path)
    source_revision = require_string(source_revision, "source revision")
    selected_providers = selected_values(provider_selection, tuple(sorted(ADAPTERS)))
    if provider_version_override is not None and len(selected_providers) != 1:
        raise SdkGeneratorError("--provider-version requires one explicit provider")

    openapi_digest = sha256_file(openapi_path)
    generation_digest = sha256_file(generation_path)
    policy_digest = optional_policy_sha256(generation)
    provenance: list[dict[str, Any]] = []
    for provider_id in selected_providers:
        provider = providers[provider_id]
        adapter_config = require_mapping(provider.get("adapter"), f"{provider_id}.adapter")
        for language in selected_provider_languages(provider_id, language_selection):
            relative_output = Path(provider_id) / language
            confined_output(safe_root, relative_output, "provider output directory")
            provenance.append(
                {
                    "adapterContractVersion": adapter_config["contractVersion"],
                    "connectedGeneration": "not-run",
                    "generationConfigSha256": generation_digest,
                    "language": language,
                    "openapiSha256": openapi_digest,
                    "optionalPolicySha256": policy_digest,
                    "outputDirectory": relative_output.as_posix(),
                    "provider": provider_id,
                    "providerRole": ADAPTERS[provider_id].role,
                    "providerVersion": provider_version(provider, provider_version_override),
                    "sourceRevision": source_revision,
                }
            )

    spec = require_mapping(generation["spec"], "generation.spec")
    optional = require_mapping(spec["optionalRestGeneration"], "optionalRestGeneration")
    parity = require_mapping(optional.get("parity"), "optionalRestGeneration.parity")
    operations = operation_contracts(openapi)
    dispositions = operation_dispositions(optional, operations)
    operation_inventory: list[dict[str, Any]] = []
    for operation in operations:
        operation_id = cast(str, operation["operationId"])
        disposition = dispositions[operation_id]
        record = dict(operation)
        record["providerDisposition"] = disposition["disposition"]
        if "reason" in disposition:
            record["reviewedReason"] = disposition["reason"]
        operation_inventory.append(record)
    return {
        "schemaVersion": PLAN_SCHEMA_VERSION,
        "kind": "OptionalRestSdkPlan",
        "authority": {
            "protobufSources": ["protocols/proto", "protocols/events"],
            "generatedRoot": "protocols/generated",
            "internalSdkRoot": "sdks",
            "nativeGenerator": "buf.gen.yaml",
            "openapiProjection": DEFAULT_OPENAPI.as_posix(),
            "openapiSha256": openapi_digest,
            "generationConfig": DEFAULT_GENERATION.as_posix(),
            "generationConfigSha256": generation_digest,
            "optionalPolicy": OPTIONAL_POLICY_SOURCE,
            "optionalPolicySha256": policy_digest,
        },
        "inventory": {
            "operationIds": [record["operationId"] for record in operation_inventory],
            "operations": operation_inventory,
            "providerEligibleOperationIds": [
                record["operationId"]
                for record in operation_inventory
                if record["providerDisposition"] == "eligible"
            ],
            "reviewedUnsupportedOperationIds": [
                record["operationId"]
                for record in operation_inventory
                if record["providerDisposition"] == "reviewed-unsupported"
            ],
            "publicSchemas": list(public_schemas(openapi)),
        },
        "provenance": provenance,
        "parity": {
            "reference": parity.get("reference"),
            "compare": sorted(
                require_string(value, "parity.compare item")
                for value in require_sequence(parity.get("compare"), "parity.compare")
            ),
            "failurePolicy": parity.get("failurePolicy"),
        },
        "safety": {
            "authoritative": False,
            "enabledByDefault": False,
            "emitsSdkSource": False,
            "network": "forbidden",
            "publishAuthorized": False,
        },
    }


def require_digest(value: Any, location: str) -> str:
    digest = require_string(value, location)
    if len(digest) != 71 or not digest.startswith("sha256:"):
        raise SdkGeneratorError(f"{location} must be a sha256:<64 lowercase hex> digest")
    if any(character not in "0123456789abcdef" for character in digest[7:]):
        raise SdkGeneratorError(f"{location} must be a sha256:<64 lowercase hex> digest")
    return digest


def generate_connected(args: argparse.Namespace) -> int:
    if not args.allow_connected:
        raise ConnectedGenerationError("connected optional generation requires --allow-connected")
    if args.provider == "all" or args.language == "all":
        raise ConnectedGenerationError(
            "connected optional generation requires one provider and one language"
        )
    if not 1 <= args.timeout_seconds <= 3600:
        raise ConnectedGenerationError("provider timeout must be between 1 and 3600 seconds")

    openapi_path = Path(args.openapi).resolve()
    generation_path = Path(args.generation).resolve()
    openapi = load_yaml_mapping(openapi_path)
    generation = load_yaml_mapping(generation_path)
    providers = validate_contract(openapi, generation)
    optional = require_mapping(
        require_mapping(generation.get("spec"), "generation.spec").get("optionalRestGeneration"),
        "optionalRestGeneration",
    )
    dispositions = operation_dispositions(optional, operation_contracts(openapi))
    unsupported = sorted(
        operation_id
        for operation_id, disposition in dispositions.items()
        if disposition["disposition"] != "eligible"
    )
    if unsupported:
        raise ConnectedGenerationError(
            "connected optional generation requires a qualified stream-capable adapter or a "
            f"descriptor-derived filtered input; reviewed-unsupported operations: {unsupported}"
        )
    provider = providers[args.provider]
    if args.language not in ADAPTERS[args.provider].languages:
        raise ConnectedGenerationError(
            f"{args.provider} does not support configured language {args.language}"
        )
    if provider.get("readiness") != "pinned-local-adapter":
        raise ConnectedGenerationError(
            f"{args.provider} is {provider.get('readiness')}; no pinned adapter may execute"
        )
    adapter = require_mapping(provider.get("adapter"), f"{args.provider}.adapter")
    configured_executable = adapter.get("executable")
    configured_digest = adapter.get("executableSha256")
    if not isinstance(configured_executable, str) or not isinstance(configured_digest, str):
        raise ConnectedGenerationError("provider executable and digest must be pinned")
    configured_digest = require_digest(configured_digest, "provider.adapter.executableSha256")
    if not args.provider_command:
        raise ConnectedGenerationError("provider command is required")
    executable = Path(args.provider_command[0]).resolve()
    if executable.as_posix() != configured_executable:
        raise ConnectedGenerationError("provider executable differs from checked-in configuration")
    if not executable.is_file() or sha256_file(executable) != configured_digest:
        raise ConnectedGenerationError("provider executable digest mismatch")
    configured_version = provider_version(provider, None)
    if configured_version == UNPINNED_VERSION:
        raise ConnectedGenerationError("provider version must be pinned")

    safe_root = validate_output_root(Path(args.output_root), openapi_path)
    relative_output = Path(args.provider) / args.language
    output_directory = confined_output(safe_root, relative_output, "provider output directory")
    output_directory.mkdir(parents=True, exist_ok=True)
    openapi_digest = sha256_file(openapi_path)
    generation_digest = sha256_file(generation_path)
    environment = {
        "LANG": "C",
        "LC_ALL": "C",
        "TZ": "UTC",
        "MINDCLADE_OPENAPI_PATH": openapi_path.as_posix(),
        "MINDCLADE_GENERATION_CONFIG_PATH": generation_path.as_posix(),
        "MINDCLADE_SDK_LANGUAGE": args.language,
        "MINDCLADE_SDK_OUTPUT_DIRECTORY": output_directory.as_posix(),
        "MINDCLADE_SDK_PROVIDER": args.provider,
    }
    try:
        result = subprocess.run(
            args.provider_command,
            check=False,
            cwd=output_directory,
            env=environment,
            timeout=args.timeout_seconds,
        )
    except subprocess.TimeoutExpired as error:
        raise ConnectedGenerationError(
            f"{args.provider} adapter exceeded {args.timeout_seconds}s timeout"
        ) from error
    if result.returncode != 0:
        raise ConnectedGenerationError(
            f"{args.provider} adapter exited with status {result.returncode}"
        )
    if (
        sha256_file(openapi_path) != openapi_digest
        or sha256_file(generation_path) != generation_digest
    ):
        raise ConnectedGenerationError("provider mutated an authoritative input")
    provenance = {
        "schemaVersion": PROVENANCE_SCHEMA_VERSION,
        "generationConfigSha256": generation_digest,
        "language": args.language,
        "openapiSha256": openapi_digest,
        "optionalPolicySha256": optional_policy_sha256(generation),
        "provider": args.provider,
        "providerExecutableSha256": configured_digest,
        "providerRole": ADAPTERS[args.provider].role,
        "providerVersion": configured_version,
        "sourceRevision": require_string(args.source_revision, "source revision"),
    }
    write_atomic(
        safe_root,
        relative_output / "mindclade-optional-rest-sdk-provenance.json",
        canonical_json(provenance),
    )
    return 0


def add_common_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--openapi", type=Path, default=DEFAULT_OPENAPI)
    parser.add_argument("--generation", type=Path, default=DEFAULT_GENERATION)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--source-revision", required=True)
    parser.add_argument("--provider", choices=("all", *sorted(ADAPTERS)), default="all")
    parser.add_argument("--language", choices=("all", *OPTIONAL_LANGUAGES), default="all")
    parser.add_argument("--provider-version")


def parser() -> argparse.ArgumentParser:
    root_parser = argparse.ArgumentParser(description=__doc__)
    commands = root_parser.add_subparsers(dest="command", required=True)
    plan = commands.add_parser("plan", help="emit an offline optional REST SDK plan")
    add_common_arguments(plan)
    plan.add_argument("--output", type=Path, default=DEFAULT_PLAN)
    verify = commands.add_parser("verify", help="verify an optional REST SDK plan")
    add_common_arguments(verify)
    verify.add_argument("--plan", type=Path, default=DEFAULT_PLAN)
    generate = commands.add_parser(
        "generate", help="guarded boundary for a pinned optional provider"
    )
    add_common_arguments(generate)
    generate.add_argument("--allow-connected", action="store_true")
    generate.add_argument("--timeout-seconds", type=int, default=900)
    generate.add_argument("--provider-command", nargs=argparse.REMAINDER)
    return root_parser


def plan_from_args(args: argparse.Namespace) -> dict[str, Any]:
    return build_plan(
        openapi_path=Path(args.openapi),
        generation_path=Path(args.generation),
        output_root=Path(args.output_root),
        source_revision=args.source_revision,
        provider_selection=args.provider,
        language_selection=args.language,
        provider_version_override=args.provider_version,
    )


def fail(message: str, exit_code: int) -> NoReturn:
    print(f"sdk-generator: {message}", file=sys.stderr)
    raise SystemExit(exit_code)


def main(argv: Sequence[str] | None = None) -> int:
    arguments = parser().parse_args(argv)
    try:
        if arguments.command == "plan":
            plan = plan_from_args(arguments)
            safe_root = validate_output_root(Path(arguments.output_root), Path(arguments.openapi))
            destination = write_atomic(safe_root, Path(arguments.output), canonical_json(plan))
            print(destination)
            return 0
        if arguments.command == "verify":
            expected = canonical_json(plan_from_args(arguments))
            safe_root = validate_output_root(Path(arguments.output_root), Path(arguments.openapi))
            plan_path = confined_output(safe_root, Path(arguments.plan), "plan")
            if not plan_path.is_file():
                fail(f"plan does not exist: {plan_path}", EXIT_VERIFY_MISMATCH)
            if plan_path.read_bytes() != expected:
                fail("plan differs from canonical config projection", EXIT_VERIFY_MISMATCH)
            print(plan_path)
            return 0
        if arguments.command == "generate":
            return generate_connected(arguments)
        fail(f"unsupported command: {arguments.command}", EXIT_USAGE)
    except ConnectedGenerationError as error:
        fail(str(error), EXIT_CONNECTED_NOT_READY)
    except (OSError, SdkGeneratorError, subprocess.TimeoutExpired) as error:
        fail(str(error), EXIT_USAGE)


if __name__ == "__main__":
    raise SystemExit(main())
