"""Code generated by tools/codegen/generate_cross_field_constraints.py. DO NOT EDIT.
Source: protocols/constraints/cross-field.yaml
Descriptor: sha256:46514bdee27df6f41f03b63f050b2cfcb95867fc8f291fe943eaf2019693c0ed"""

from __future__ import annotations

from typing import Any, Final


class CrossFieldError(ValueError):
    """One unsatisfied cross-field constraint.

    ``constraint`` is the same identifier every other language reports, so a
    facade error and a server error name the same rule.
    """

    def __init__(self, constraint: str, message: str, rule: str, fields: list[str]) -> None:
        super().__init__(f"{constraint}: {rule} on {message}: {', '.join(fields)}")
        self.constraint = constraint
        self.message_type = message
        self.rule = rule
        self.fields = fields


# The generated projection of protocols/constraints/cross-field.yaml. Nothing
# may add to it by hand: a rule present in one language and absent in another
# is the failure this table exists to prevent.
CrossFieldRule = tuple[str, str, str, tuple[tuple[str, ...], ...]]

CROSS_FIELD_RULES: Final[tuple[CrossFieldRule, ...]] = (
    (
        "agent-definition-create-rejects-output-only-fields",
        "mindclade.internal.agent.v1.CreateAgentDefinitionRequest",
        "output-only",
        (
            ("agent_definition", "name"),
            ("agent_definition", "uid"),
            ("agent_definition", "revision"),
            ("agent_definition", "etag"),
            ("agent_definition", "tenant_id"),
            ("agent_definition", "project_id"),
            ("agent_definition", "create_time"),
            ("agent_definition", "update_time"),
            ("agent_definition", "delete_time"),
        ),
    ),
    (
        "approval-request-create-rejects-output-only-fields",
        "mindclade.internal.workflow.v1.RequestApprovalRequest",
        "output-only",
        (
            ("approval_request", "name"),
            ("approval_request", "uid"),
            ("approval_request", "revision"),
            ("approval_request", "etag"),
            ("approval_request", "tenant_id"),
            ("approval_request", "project_id"),
            ("approval_request", "requested_at"),
        ),
    ),
    (
        "project-create-rejects-output-only-fields",
        "mindclade.internal.admin.v1.CreateProjectRequest",
        "output-only",
        (
            ("project", "name"),
            ("project", "uid"),
            ("project", "revision"),
            ("project", "etag"),
            ("project", "create_time"),
            ("project", "update_time"),
            ("project", "delete_time"),
        ),
    ),
    (
        "promotion-decision-create-rejects-output-only-fields",
        "mindclade.internal.evaluation.v1.CreatePromotionDecisionRequest",
        "output-only",
        (
            ("promotion_decision", "name"),
            ("promotion_decision", "uid"),
        ),
    ),
    (
        "use-policy-create-rejects-output-only-fields",
        "mindclade.internal.policy.v1.CreateUsePolicyRequest",
        "output-only",
        (
            ("use_policy", "name"),
            ("use_policy", "uid"),
            ("use_policy", "revision"),
            ("use_policy", "etag"),
            ("use_policy", "tenant_id"),
            ("use_policy", "project_id"),
            ("use_policy", "create_time"),
            ("use_policy", "update_time"),
            ("use_policy", "delete_time"),
        ),
    ),
    (
        "workflow-definition-create-rejects-output-only-fields",
        "mindclade.internal.workflow.v1.CreateWorkflowDefinitionRequest",
        "output-only",
        (
            ("workflow_definition", "name"),
            ("workflow_definition", "uid"),
            ("workflow_definition", "revision"),
            ("workflow_definition", "etag"),
            ("workflow_definition", "tenant_id"),
            ("workflow_definition", "project_id"),
            ("workflow_definition", "create_time"),
            ("workflow_definition", "update_time"),
            ("workflow_definition", "delete_time"),
        ),
    ),
)


def _is_set(message: Any, path: tuple[str, ...]) -> bool:
    """Proto3 presence: set means "not the zero value".

    A path that stops at an absent message is unset rather than an error --
    an unset parent cannot have a set child.
    """

    current: Any = message
    for index, name in enumerate(path):
        descriptor = current.DESCRIPTOR.fields_by_name.get(name)
        if descriptor is None:
            return False
        if index == len(path) - 1:
            if descriptor.message_type is not None:
                return current.HasField(name)
            return bool(getattr(current, name))
        if not current.HasField(name):
            return False
        current = getattr(current, name)
    return False


def _violated(rule: str, count: int, total: int) -> bool:
    if rule == "output-only":
        return count > 0
    if rule == "conflicts-with":
        return count > 1
    if rule == "xor-with":
        return count != 1
    if rule == "required-with":
        return count not in (0, total)
    return False


def validate_cross_field(message: Any) -> None:
    """Check every constraint declared for this message type.

    A message with no constraints passes, so the caller need not know which
    types carry rules.
    """

    if message is None:
        return
    name = message.DESCRIPTOR.full_name
    for constraint, declared, rule, paths in CROSS_FIELD_RULES:
        if declared != name:
            continue
        present = [_join(path) for path in paths if _is_set(message, path)]
        if _violated(rule, len(present), len(paths)):
            raise CrossFieldError(
                constraint, declared, rule, present or [_join(path) for path in paths]
            )


def _join(path: tuple[str, ...]) -> str:
    return ".".join(path)
