"""Immutable compile-time contracts for the Mindclade kernel platform.

This package has no TileLang, Torch, CUDA, discovery, compilation, tuning, or
registration side effects.  Operation declarations may import only these data
contracts and construct one canonical ``KernelSpec`` in ``spec.py``.
"""

from .backward import BackwardSpec
from .capability import CapabilityEnvelope, DimensionConstraint
from .effects import EffectSpec
from .environment import CompileEnvironment, DeviceCapabilities, RuntimeCompatibility
from .errors import (
    ExpressionCodegenError,
    ExpressionDecodeError,
    ExpressionError,
    ExpressionEvaluationError,
    ExpressionValidationError,
    KernelContractError,
    SchemaError,
)
from .expressions import (
    Add,
    And,
    BoolExpr,
    BoolLiteral,
    CeilDiv,
    ConstantDType,
    ConstantDevice,
    DeviceExpr,
    DeviceRef,
    DimRef,
    DTypeExpr,
    DTypeRef,
    Eq,
    EvaluationContext,
    Expr,
    ExprDomain,
    FloatLiteral,
    FloorDiv,
    GreaterEqual,
    GreaterThan,
    InSet,
    IntExpr,
    IntLiteral,
    LessEqual,
    LessThan,
    Maximum,
    Minimum,
    Modulo,
    Multiply,
    Not,
    NotEqual,
    Or,
    RankRef,
    RoundUp,
    SameAsInputDType,
    SameAsInputDevice,
    ScalarRef,
    ScalarType,
    Select,
    ShapeExpr,
    StringLiteral,
    Subtract,
    TensorMetadata,
    canonical_data,
    canonical_json,
    content_digest,
    evaluate,
    expression_from_data,
    expression_from_json,
    generate_native_host_validator,
    generate_python_validator,
    render,
)
from .forward import ForwardSpec
from .gradient import GradientSpec
from .implementation import ImplementationSpec, ImplementationTier
from .kernel import AutogradPolicy, CompositeAutogradSpec, KernelSpec
from .launch import DeterminismClass, LaunchContract
from .numerics import NumericalEnvelope, TensorTolerance
from .output import ContractModel, InitializationSpec, OutputSpec
from .program_group import ProgramGroupSpec, ProgramNodeSpec, WorkspaceSpec
from .qualification import QualifiedCapability
from .schedule import ScheduleSpec, SpecializationSpec
from .workload import ScalarValue, WorkloadSpec

__all__ = (
    "Add",
    "And",
    "AutogradPolicy",
    "BackwardSpec",
    "BoolExpr",
    "BoolLiteral",
    "CapabilityEnvelope",
    "CeilDiv",
    "CompileEnvironment",
    "CompositeAutogradSpec",
    "ConstantDType",
    "ConstantDevice",
    "ContractModel",
    "DTypeExpr",
    "DTypeRef",
    "DeterminismClass",
    "DeviceCapabilities",
    "DeviceExpr",
    "DeviceRef",
    "DimRef",
    "DimensionConstraint",
    "EffectSpec",
    "Eq",
    "EvaluationContext",
    "Expr",
    "ExprDomain",
    "ExpressionCodegenError",
    "ExpressionDecodeError",
    "ExpressionError",
    "ExpressionEvaluationError",
    "ExpressionValidationError",
    "FloatLiteral",
    "FloorDiv",
    "ForwardSpec",
    "GradientSpec",
    "GreaterEqual",
    "GreaterThan",
    "ImplementationSpec",
    "ImplementationTier",
    "InSet",
    "IntExpr",
    "IntLiteral",
    "KernelContractError",
    "KernelSpec",
    "LaunchContract",
    "LessEqual",
    "LessThan",
    "Maximum",
    "Minimum",
    "Modulo",
    "Multiply",
    "Not",
    "NotEqual",
    "NumericalEnvelope",
    "Or",
    "OutputSpec",
    "InitializationSpec",
    "ProgramGroupSpec",
    "ProgramNodeSpec",
    "QualifiedCapability",
    "RankRef",
    "RoundUp",
    "RuntimeCompatibility",
    "SameAsInputDType",
    "SameAsInputDevice",
    "ScalarRef",
    "ScalarType",
    "ScalarValue",
    "ScheduleSpec",
    "SchemaError",
    "Select",
    "ShapeExpr",
    "SpecializationSpec",
    "StringLiteral",
    "Subtract",
    "TensorMetadata",
    "TensorTolerance",
    "WorkloadSpec",
    "WorkspaceSpec",
    "canonical_data",
    "canonical_json",
    "content_digest",
    "evaluate",
    "expression_from_data",
    "expression_from_json",
    "generate_native_host_validator",
    "generate_python_validator",
    "render",
)

