package audit

import (
	"context"
	"fmt"
	"sync"

	"google.golang.org/protobuf/proto"

	commonv1 "github.com/mindclade/mindclade/protocols/generated/go/common/v1"
)

type Writer interface {
	Append(context.Context, *commonv1.EventEnvelope) error
}

// MemoryWriter stores immutable generated bytes, matching the permitted audit
// evidence boundary without making protobuf the business-state database model.
type MemoryWriter struct {
	mu     sync.Mutex
	events [][]byte
}

func (w *MemoryWriter) Append(ctx context.Context, event *commonv1.EventEnvelope) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if _, err := ValidateEvent(event); err != nil {
		return err
	}
	encoded, err := proto.MarshalOptions{Deterministic: true}.Marshal(event)
	if err != nil {
		return fmt.Errorf("marshal audit envelope: %w", err)
	}
	w.mu.Lock()
	defer w.mu.Unlock()
	w.events = append(w.events, encoded)
	return nil
}

func (w *MemoryWriter) Events() ([]*commonv1.EventEnvelope, error) {
	w.mu.Lock()
	defer w.mu.Unlock()
	result := make([]*commonv1.EventEnvelope, len(w.events))
	for index, encoded := range w.events {
		result[index] = new(commonv1.EventEnvelope)
		if err := proto.Unmarshal(encoded, result[index]); err != nil {
			return nil, fmt.Errorf("unmarshal audit envelope: %w", err)
		}
	}
	return result, nil
}
