name: Dependency review

on:
  pull_request:
    paths:
      - "**/MODULE.bazel"
      - "**/MODULE.bazel.lock"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/buf.lock"
      - "**/flake.lock"
      - "**/go.mod"
      - "**/go.sum"
      - "**/package.json"
      - "**/pnpm-lock.yaml"
      - "**/pnpm-workspace.yaml"
      - "**/pyproject.toml"
      - "**/uv.lock"
      - ".github/renovate.json"

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-dependency-review-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  review:
    uses: mindclade/.github/.github/workflows/reusable-dependency-review.yml@cdfc7303e8f14d647528774768c144e4dbf67b86
    with:
      source_revision: ${{ github.event.pull_request.head.sha }}
      base_revision: ${{ github.event.pull_request.base.sha }}
