name: Documentation

on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
      - "tools/docs/**"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "docs/**"
      - "tools/docs/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-documentation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    uses: mindclade/.github/.github/workflows/reusable-documentation-check.yml@fc5af9efc19b47078fe446feee750d7f4973195b
    with:
      source_revision: ${{ github.event.pull_request.head.sha || github.sha }}
      documentation_roots: |-
        README.md
        docs
