name: Documentation

on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
      - "tools/docs/**"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "docs/**"
      - "tools/docs/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-documentation-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    uses: mindclade/.github/.github/workflows/reusable-documentation-check.yml@6399abc50c4678d0dff7f33bbd7f6868043ef736
    with:
      source_revision: ${{ github.event.pull_request.head.sha || github.sha }}
      documentation_roots: |-
        README.md
        docs
