name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "31 6 * * 3"

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-scorecard-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    permissions:
      contents: read
      security-events: write
    uses: mindclade/.github/.github/workflows/reusable-scorecard.yml@f9b6ebcecd197157d9466eeacf8e2864e32c9a79
    with:
      source_revision: ${{ github.sha }}
