load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "pubsubx",
    srcs = glob(
        ["*.go"],
        exclude = ["*_test.go"],
    ),
    importpath = "github.com/mindclade/mindclade/libs/go/pubsubx",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/go/persistence",
        "//protocols/generated/go/common/v1:bindings",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
    ],
)

filegroup(
    name = "governed_sources",
    srcs = ["BUILD.bazel"] + glob(
        ["**"],
        exclude = ["BUILD.bazel"],
    ),
    visibility = ["//visibility:public"],
)
